## Author: Tianheng Zhou

# 1. Read Data from S3 Bucket

In [1]:
from sagemaker import get_execution_role
role = get_execution_role()

#Bucket and Folder
bucket = 'project-b-data'
subfolder = 'proj-b/dataset-b01'

In [2]:
import boto3
conn = boto3.client('s3')
contents = conn.list_objects(Bucket=bucket, Prefix=subfolder)['Contents']
#Data Set Name
for i in range(5):
    print(contents[i]['Key'])

proj-b/dataset-b01/README.txt
proj-b/dataset-b01/Tst2022-01-04LOBs.txt
proj-b/dataset-b01/Tst2022-01-04tapes.csv
proj-b/dataset-b01/Tst2022-01-05LOBs.txt
proj-b/dataset-b01/Tst2022-01-05tapes.csv

## 1.1 Read all the csv data

In [3]:
#Generate String Date
import pandas as pd
date_list = pd.date_range(start = "2022-01-04",end = "2022-04-29").tolist()
exact_date = [str(i)[0:10] for i in date_list]   #2022-01-04 format"
print(exact_date[:5])

['2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08']

In [4]:
import time

In [4]:
#Read the dataset of tapes.csv file


# tape_csv = []

# total_time = 0
# for the_date in exact_date:
#     t1 = time.time()
#     tape_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/Tst'+the_date+'tapes.csv')

#     try: 
#         tape_csv.append(pd.DataFrame(pd.read_csv(tape_from_s3,header = None)))
#     except:
#         continue
#     t2 = time.time()
#     total_time += t2 - t1
#     print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

# print("Total .csv file Read time: {}".format(total_time))

The 2022-01-04 is finished. Elapsed time is 1.1625711917877197 seconds.
The 2022-01-05 is finished. Elapsed time is 0.5130982398986816 seconds.
The 2022-01-06 is finished. Elapsed time is 0.48949337005615234 seconds.
The 2022-01-07 is finished. Elapsed time is 0.5533671379089355 seconds.
The 2022-01-10 is finished. Elapsed time is 0.6875514984130859 seconds.
The 2022-01-11 is finished. Elapsed time is 0.5011980533599854 seconds.
The 2022-01-12 is finished. Elapsed time is 0.5552902221679688 seconds.
The 2022-01-13 is finished. Elapsed time is 0.6046521663665771 seconds.
The 2022-01-14 is finished. Elapsed time is 0.8985393047332764 seconds.
The 2022-01-17 is finished. Elapsed time is 0.8706321716308594 seconds.
The 2022-01-18 is finished. Elapsed time is 0.4898977279663086 seconds.
The 2022-01-19 is finished. Elapsed time is 0.5468220710754395 seconds.
The 2022-01-20 is finished. Elapsed time is 0.6237328052520752 seconds.
The 2022-01-21 is finished. Elapsed time is 0.4842534065246582 seconds.
The 2022-01-24 is finished. Elapsed time is 0.5584392547607422 seconds.
The 2022-01-25 is finished. Elapsed time is 0.621880054473877 seconds.
The 2022-01-26 is finished. Elapsed time is 0.5469613075256348 seconds.
The 2022-01-27 is finished. Elapsed time is 0.6165225505828857 seconds.
The 2022-01-28 is finished. Elapsed time is 0.5517215728759766 seconds.
The 2022-01-31 is finished. Elapsed time is 0.4692237377166748 seconds.
The 2022-02-01 is finished. Elapsed time is 0.7944827079772949 seconds.
The 2022-02-02 is finished. Elapsed time is 0.5055651664733887 seconds.
The 2022-02-03 is finished. Elapsed time is 0.5058238506317139 seconds.
The 2022-02-04 is finished. Elapsed time is 0.4597797393798828 seconds.
The 2022-02-07 is finished. Elapsed time is 0.6038827896118164 seconds.
The 2022-02-08 is finished. Elapsed time is 0.547642707824707 seconds.
The 2022-02-09 is finished. Elapsed time is 0.6244544982910156 seconds.
The 2022-02-10 is finished. Elapsed time is 0.520756721496582 seconds.
The 2022-02-11 is finished. Elapsed time is 0.644721508026123 seconds.
The 2022-02-14 is finished. Elapsed time is 0.5727989673614502 seconds.
The 2022-02-15 is finished. Elapsed time is 0.5913476943969727 seconds.
The 2022-02-16 is finished. Elapsed time is 0.7022826671600342 seconds.
The 2022-02-17 is finished. Elapsed time is 0.5942063331604004 seconds.
The 2022-02-18 is finished. Elapsed time is 0.6454031467437744 seconds.
The 2022-02-21 is finished. Elapsed time is 0.606895923614502 seconds.
The 2022-02-22 is finished. Elapsed time is 0.5230011940002441 seconds.
The 2022-02-23 is finished. Elapsed time is 0.6686844825744629 seconds.
The 2022-02-24 is finished. Elapsed time is 0.6528620719909668 seconds.
The 2022-02-25 is finished. Elapsed time is 0.5296196937561035 seconds.
The 2022-03-01 is finished. Elapsed time is 0.5484709739685059 seconds.
The 2022-03-02 is finished. Elapsed time is 0.7863707542419434 seconds.
The 2022-03-03 is finished. Elapsed time is 0.6477863788604736 seconds.
The 2022-03-04 is finished. Elapsed time is 0.562382698059082 seconds.
The 2022-03-07 is finished. Elapsed time is 0.5644845962524414 seconds.
The 2022-03-08 is finished. Elapsed time is 1.0046653747558594 seconds.
The 2022-03-09 is finished. Elapsed time is 0.6497015953063965 seconds.
The 2022-03-10 is finished. Elapsed time is 0.5219936370849609 seconds.
The 2022-03-11 is finished. Elapsed time is 0.7991888523101807 seconds.
The 2022-03-14 is finished. Elapsed time is 0.6475846767425537 seconds.
The 2022-03-15 is finished. Elapsed time is 0.6052050590515137 seconds.
The 2022-03-16 is finished. Elapsed time is 0.4960970878601074 seconds.
The 2022-03-17 is finished. Elapsed time is 0.8552305698394775 seconds.
The 2022-03-18 is finished. Elapsed time is 0.6236286163330078 seconds.
The 2022-03-21 is finished. Elapsed time is 0.610790491104126 seconds.
The 2022-03-22 is finished. Elapsed time is 0.4513981342315674 seconds.
The 2022-03-23 is finished. Elapsed time is 0.490952730178833 seconds.
The 2022-03-24 is finished. Elapsed time is 0.7208869457244873 seconds.
The 2022-03-25 is finished. Elapsed time is 0.46438145637512207 seconds.
The 2022-03-28 is finished. Elapsed time is 0.542170524597168 seconds.
The 2022-03-29 is finished. Elapsed time is 0.644500732421875 seconds.
The 2022-03-30 is finished. Elapsed time is 0.472027063369751 seconds.
The 2022-03-31 is finished. Elapsed time is 0.4053044319152832 seconds.
The 2022-04-01 is finished. Elapsed time is 0.5587568283081055 seconds.
The 2022-04-04 is finished. Elapsed time is 0.5040514469146729 seconds.
The 2022-04-05 is finished. Elapsed time is 0.8419101238250732 seconds.
The 2022-04-06 is finished. Elapsed time is 1.0277423858642578 seconds.
The 2022-04-07 is finished. Elapsed time is 1.0912606716156006 seconds.
The 2022-04-08 is finished. Elapsed time is 1.010197401046753 seconds.
The 2022-04-11 is finished. Elapsed time is 1.094512939453125 seconds.
The 2022-04-12 is finished. Elapsed time is 0.8292243480682373 seconds.
The 2022-04-13 is finished. Elapsed time is 0.5192131996154785 seconds.
The 2022-04-14 is finished. Elapsed time is 0.6586260795593262 seconds.
The 2022-04-19 is finished. Elapsed time is 0.5772736072540283 seconds.
The 2022-04-20 is finished. Elapsed time is 0.6854286193847656 seconds.
The 2022-04-21 is finished. Elapsed time is 0.6142747402191162 seconds.
The 2022-04-22 is finished. Elapsed time is 0.6230504512786865 seconds.
The 2022-04-25 is finished. Elapsed time is 0.5397427082061768 seconds.
The 2022-04-26 is finished. Elapsed time is 0.5243301391601562 seconds.
The 2022-04-27 is finished. Elapsed time is 0.5695312023162842 seconds.
The 2022-04-28 is finished. Elapsed time is 0.5609011650085449 seconds.
The 2022-04-29 is finished. Elapsed time is 0.5142319202423096 seconds.
Total .csv file Read time: 51.099523067474365

In [6]:
#Concatenate all the csv file into one data frame 


# full_csv_frame = pd.concat(tape_csv)
# print("There are {} rows and {} columns of the full csv frame.".format(full_csv_frame.shape[0],full_csv_frame.shape[1]))
# print(full_csv_frame[:5])
# full_csv_frame.to_csv("Tape_csv/Full_tape.csv")

There are 5230364 rows and 11 columns of the full csv frame.
              0          1       2    3                        4   \
0  Tst2022-01-04   Exch0Lit   8.192  203   {'pool_id': 'Exch0Lit'
1  Tst2022-01-04   Exch0Lit   8.192  199   {'pool_id': 'Exch0Lit'
2  Tst2022-01-04   Exch0Lit  10.336  196   {'pool_id': 'Exch0Lit'
3  Tst2022-01-04   Exch0Lit  10.672  196   {'pool_id': 'Exch0Lit'
4  Tst2022-01-04   Exch0Lit  11.040  201   {'pool_id': 'Exch0Lit'

                 5                6              7          8   \
0   'type': 'Trade'    'time': 8.192   'price': 203   'qty': 2
1   'type': 'Trade'    'time': 8.192   'price': 199   'qty': 3
2   'type': 'Trade'   'time': 10.336   'price': 196   'qty': 3
3   'type': 'Trade'   'time': 10.672   'price': 196   'qty': 4
4   'type': 'Trade'    'time': 11.04   'price': 201   'qty': 1

                 9                  10
0   'party1': 'S26'   'party2': 'B24'}
1   'party1': 'S26'   'party2': 'B08'}
2   'party1': 'S06'   'party2': 'B07'}
3   'party1': 'S01'   'party2': 'B01'}
4   'party1': 'S12'   'party2': 'B31'}

In [7]:
# pd.read_csv("Tape_csv/Full_tape.csv")

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10
0,0,Tst2022-01-04,Exch0Lit,8.192,203,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 203,'qty': 2,'party1': 'S26','party2': 'B24'}
1,1,Tst2022-01-04,Exch0Lit,8.192,199,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 199,'qty': 3,'party1': 'S26','party2': 'B08'}
2,2,Tst2022-01-04,Exch0Lit,10.336,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.336,'price': 196,'qty': 3,'party1': 'S06','party2': 'B07'}
3,3,Tst2022-01-04,Exch0Lit,10.672,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.672,'price': 196,'qty': 4,'party1': 'S01','party2': 'B01'}
4,4,Tst2022-01-04,Exch0Lit,11.040,201,{'pool_id': 'Exch0Lit','type': 'Trade','time': 11.04,'price': 201,'qty': 1,'party1': 'S12','party2': 'B31'}
...,...,...,...,...,...,...,...,...,...,...,...,...
5230359,64888,Tst2022-04-29,Exch0Lit,30599.376,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.376,'price': 134,'qty': 1,'party1': 'S21','party2': 'B07'}
5230360,64889,Tst2022-04-29,Exch0Lit,30599.520,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.52,'price': 134,'qty': 1,'party1': 'S03','party2': 'B07'}
5230361,64890,Tst2022-04-29,Exch0Lit,30599.584,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.584,'price': 134,'qty': 1,'party1': 'S28','party2': 'B01'}
5230362,64891,Tst2022-04-29,Exch0Lit,30599.776,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 134,'qty': 3,'party1': 'S04','party2': 'B01'}
5230363,64892,Tst2022-04-29,Exch0Lit,30599.776,133,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 133,'qty': 1,'party1': 'S04','party2': 'B19'}

In [8]:
# import boto3
# s3 = boto3.Session().resource('s3')
# key = 'proj-b/Tape_csv/Full_tape.csv' # filepath in s3
# doc = "Tape_csv/Full_tape.csv"# your local file

# s3.Bucket('project-b-data').Object(key).upload_file(doc)

In [10]:
# %%time
# pd.read_csv('s3://{}/{}'.format('project-b-data','proj-b/Tape_csv/Full_tape.csv'))

CPU times: user 13 s, sys: 2.74 s, total: 15.8 s
Wall time: 49.5 s

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10
0,0,Tst2022-01-04,Exch0Lit,8.192,203,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 203,'qty': 2,'party1': 'S26','party2': 'B24'}
1,1,Tst2022-01-04,Exch0Lit,8.192,199,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 199,'qty': 3,'party1': 'S26','party2': 'B08'}
2,2,Tst2022-01-04,Exch0Lit,10.336,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.336,'price': 196,'qty': 3,'party1': 'S06','party2': 'B07'}
3,3,Tst2022-01-04,Exch0Lit,10.672,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.672,'price': 196,'qty': 4,'party1': 'S01','party2': 'B01'}
4,4,Tst2022-01-04,Exch0Lit,11.040,201,{'pool_id': 'Exch0Lit','type': 'Trade','time': 11.04,'price': 201,'qty': 1,'party1': 'S12','party2': 'B31'}
...,...,...,...,...,...,...,...,...,...,...,...,...
5230359,64888,Tst2022-04-29,Exch0Lit,30599.376,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.376,'price': 134,'qty': 1,'party1': 'S21','party2': 'B07'}
5230360,64889,Tst2022-04-29,Exch0Lit,30599.520,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.52,'price': 134,'qty': 1,'party1': 'S03','party2': 'B07'}
5230361,64890,Tst2022-04-29,Exch0Lit,30599.584,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.584,'price': 134,'qty': 1,'party1': 'S28','party2': 'B01'}
5230362,64891,Tst2022-04-29,Exch0Lit,30599.776,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 134,'qty': 3,'party1': 'S04','party2': 'B01'}
5230363,64892,Tst2022-04-29,Exch0Lit,30599.776,133,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 133,'qty': 1,'party1': 'S04','party2': 'B19'}

## 1.2 Read all the LOB data

In [5]:
!pip install smart_open
!pip install ijson

import ijson
import json
import re

import smart_open as sm
#help(sm)

Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Collecting smart_open
  Downloading smart_open-5.2.1-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 11.0 MB/s
Installing collected packages: smart-open
Successfully installed smart-open-5.2.1
Looking in indexes: https://pypi.org/simple, https://pip.repos.neuron.amazonaws.com
Collecting ijson
  Downloading ijson-3.1.4-cp36-cp36m-manylinux2010_x86_64.whl (124 kB)
     |████████████████████████████████| 124 kB 29.3 MB/s
Installing collected packages: ijson
Successfully installed ijson-3.1.4

### 1.2.1 Read the Example LOB data
#### 1.2.1.1 Read the Example LOB set to see the data format.
Below is some methods that **I didn't adopt.**

In [6]:
with sm.open('Example.txt',"r",encoding='utf-8') as f:
    example_data = f.read()
print(example_data)

[
    "time",
    0.0,
    [
        "bid",
        []
    ],
    [
        "ask",
        []
    ]
]
[
    "time",
    0.016,
    [
        "bid",
        []
    ],
    [
        "ask",
        []
    ]
]
[
    "time",
    0.528,
    [
        "bid",
        [
            [
                27,
                3
            ]
        ]
    ],
    [
        "ask",
        []
    ]
]

1) Here is the way that I try to use regular expression to get the data frame of the LOB file. But the re.sub() function would have **Memory Error** if we use the full LOB file, so this way is not plausible.

In [7]:
#1. Change the file into a readable list
import ast
example_data1 = example_data.replace(']\n[',',')
example_data2 = re.sub(" ","",example_data1)
example_data3 = re.sub("\n","",example_data2)
example_data4 = re.sub(r"\s+","",example_data3)
example_data5 = re.sub('"time",','',example_data4)
example_data6 = re.sub('"bid",','',example_data5)
example_data7 = re.sub('"ask",','',example_data6)

#safely convert the nested list in string to list
example_data8 = ast.literal_eval(example_data7)  
print("List of LOB: ",example_data8)
print("Type of the Number: ",type(example_data8[0]))
print("----------------------------------------------")


#2. Extract the features in the list
example_time = []
example_bid = []
example_ask = []

for i,item in enumerate(example_data8):
    #time
    if i % 3 == 0:
        example_time.append(item)
    #bid
    elif i % 3 == 1:
        try:
            example_bid.append((item[0][0][0],item[0][0][1]))
        except:
            example_bid.append(float('nan'))
    elif i % 3 == 2 :
        try:
            example_ask.append((item[0][0][0],item[0][0][1]))
        except:
            example_ask.append(float('nan'))

example_df = pd.DataFrame([example_time,example_bid,example_ask]).T
example_df = example_df.rename(columns={0: 'Time', 1: 'Bid',2: 'Ask'})
print(example_df)

List of LOB:  [0.0, [[]], [[]], 0.016, [[]], [[]], 0.528, [[[27, 3]]], [[]]]
Type of the Number:  <class 'float'>
----------------------------------------------
    Time      Bid  Ask
0      0      NaN  NaN
1  0.016      NaN  NaN
2  0.528  (27, 3)  NaN

In [8]:
def Read_LOB_file(source):
    """
    source: S3 Bucket file address
    
    """
    t1 = time.time()
    with sm.smart_open(source,encoding='utf-8',buffering = 10000000) as f:
        LOB_data = f.read()
    f.close()
        
    LOB_data1 = LOB_data.replace(']\n[',',')
    LOB_data2 = re.sub(" ","",LOB_data1)
    LOB_data3 = re.sub("\n","",LOB_data2)
    LOB_data4 = re.sub(r"\s+","",LOB_data3)
    LOB_data5 = re.sub('"time",','',LOB_data4)
    LOB_data6 = re.sub('"bid",','',LOB_data5)
    LOB_data7 = re.sub('"ask",','',LOB_data6)

    #safely convert the nested list in string to list
    LOB_data8 = ast.literal_eval(LOB_data7)  
    t2 = time.time()
    
    print(f"Read LOB file {source} finish, the elapsed time is {t2-t1} seconds.")
    return LOB_data8

def Create_LOB_Dataframe(LOB_data,file_date):
    """
    LOB_data: The return value(list) from Read_LOB_file
    file_date: The date of the LOB file
    
    """
    t1 = time.time()
    the_time = []
    bid = []
    ask = []
    date = []
    
    for i,item in enumerate(LOB_data):
        #time
        if i % 3 == 0:
            the_time.append(item)
        #bid
        elif i % 3 == 1:
            try:
                bid.append((item[0][0][0],item[0][0][1]))
            except:
                bid.append(float('nan'))
        #ask
        elif i % 3 == 2 :
            try:
                ask.append((item[0][0][0],item[0][0][1]))
            except:
                ask.append(float('nan'))
                
    date.append(file_date)
    date = date * len(the_time)
    
    df = pd.DataFrame([date,the_time,bid,ask]).T
    df = df.rename(columns={0: 'Date',1: 'Time', 2: 'Bid',3: 'Ask'})
    t2 = time.time()
    
    print(f"Create {file_date} LOB dataframe finish, the elapsed time is {t2-t1}.")
    return df

print(Create_LOB_Dataframe(Read_LOB_file(
    'Example.txt'),'2022-01-04'))

Read LOB file Example.txt finish, the elapsed time is 0.0016112327575683594 seconds.
Create 2022-01-04 LOB dataframe finish, the elapsed time is 0.002618074417114258.
         Date   Time      Bid  Ask
0  2022-01-04      0      NaN  NaN
1  2022-01-04  0.016      NaN  NaN
2  2022-01-04  0.528  (27, 3)  NaN

2) Here is the previous try of reading the LOB data using ijson package, but I failed because changing the large LOB file into a standard json format will also cause **Memory Error**. .

In [10]:
# ijson.parse??
# def parse_json(json_filename):
#     with smart_open(json_filename, 'rb') as input_file:
#         # load json iteratively
#         parser = ijson.parse(input_file,multiple_values=True)
#         for prefix, event, value in parser:
#             print(value)
# parse_json(example_data4)

3) Here is the way I think I can directly use regular expressions to extract all the features, but because it needs to operate the full data, there will also be **Memory Error**

In [9]:
#regrex time
print("Time: ",re.findall(r'"time",\n\s*[\d]*[\.]?[\d]*',example_data))
#unfinished, regrex bid
print("Bid: ",re.findall(r'"bid",\n[\s]*\[[\]|\n\s*\[\n\s*]',example_data))

Time:  ['"time",\n    0.0', '"time",\n    0.016', '"time",\n    0.528']
Bid:  ['"bid",\n        []', '"bid",\n        []', '"bid",\n        [\n']

In [10]:
#Test regular expression
a = "123.4,0.5555566,7.85"
print(re.findall(r"[\d]+[\.]?[\d]*",a))

['123.4', '0.5555566', '7.85']

#### 1.2.1.2 Read a 1000000+ lines LOB file 
Here I would like to create a 1000000+ lines LOB subset to validate the reading method.

In [11]:
#!pip install json-stream

LOB_subset_01_04 = ""
with sm.open('s3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt',
             "r",encoding='utf-8') as f:
    for i,line in enumerate(f):        
        LOB_subset_01_04 += line
        
        #56861
        if i == 1000021:
            break
            
    f.close()

#print(LOB_subset_01_04[-1000:-1])

Try to read in meta data chunk

In [12]:
%%time
LOB_subset_time = []
LOB_subset_bid = []
LOB_subset_ask = []
time_i = -10000
bid_i = -10000
ask_i = -10000
time_change_sign = False
bid_change_sign = False
ask_change_sign = False


for i,line in enumerate(LOB_subset_01_04.splitlines()):
    if i% 100000 == 0:
        print(f"This is {i//100000}th 100000 row")
    
    #Time
    if line.strip() == '"time",':
        time_i = i 
        time_change_sign = True
        continue        
    if i == (time_i +1) and time_change_sign == True:
        time_number = re.findall(r"[\d]+[\.]?[\d]*",line)[0]
        #print(f"Time Number {time_number} Appended")
        time_change_sign = False
        LOB_subset_time.append(time_number)
        continue
        
    
    
    #Bid
    if line.strip() == '"bid",':
        bid_i = i
        bid_change_sign = True
        bid_string = ""
        continue
    if i == (bid_i + 1) and line.strip() == "[]" and bid_change_sign == True:
        #print("Bid None Appended")
        bid_change_sign = False
        LOB_subset_bid.append(None)
        continue          
    if i == (bid_i + 1) and line.strip() == "[" and bid_change_sign == True:
        bid_string += line.strip()
        continue
    elif line.strip() != "]" and bid_change_sign == True:
        bid_string += line.strip()
        continue
    elif line.strip() == "]" and bid_change_sign == True:
        bid_string += "]]"
        LOB_subset_bid.append(ast.literal_eval(bid_string))
        #print(f"Bid {bid_string} Appended")
        bid_change_sign = False
        continue
            
    #Ask
    if line.strip() == '"ask",':
        ask_i = i
        ask_change_sign = True
        ask_string = ""
        continue       
    if i == (ask_i + 1) and line.strip() == "[]" and ask_change_sign == True:
        LOB_subset_ask.append(None)
        #print("Ask None Appended")
        ask_change_sign = False
        continue       
    if i == (ask_i + 1) and line.strip() == "[" and ask_change_sign == True:
        ask_string += line.strip()
        continue
    elif line.strip() != "]" and ask_change_sign == True:
        ask_string += line.strip()
        continue
    elif line.strip() == "]" and ask_change_sign == True:
        ask_string += "]]"
        LOB_subset_ask.append(ast.literal_eval(ask_string))
        #print(f"Ask {ask_string} Appended")
        ask_change_sign = False
        continue
        
        
        

        
#     if line == "]":
#         print("-------------------Next Meta Data--------------------")

    
LOB_subset_df = pd.DataFrame([LOB_subset_time,LOB_subset_bid,LOB_subset_ask]).T
LOB_subset_df = LOB_subset_df.rename(columns={0: 'Time', 1: 'Bid',2: 'Ask'})
LOB_subset_df.to_csv("1000021_LOB_01_04.csv")
print(LOB_subset_df)

This is 0th 100000 row
This is 1th 100000 row
This is 2th 100000 row
This is 3th 100000 row
This is 4th 100000 row
This is 5th 100000 row
This is 6th 100000 row
This is 7th 100000 row
This is 8th 100000 row
This is 9th 100000 row
This is 10th 100000 row
          Time                                                Bid  \
0          0.0                                               None
1        0.016                                               None
2        0.032                                               None
3        0.048                                               None
4        0.064                                               None
...        ...                                                ...
11184  178.944  [[177, 5], [157, 1], [140, 5], [112, 1], [36, 1]]
11185   178.96  [[177, 5], [157, 1], [140, 5], [112, 1], [36, 1]]
11186  178.976  [[177, 5], [157, 1], [140, 5], [112, 1], [36, 1]]
11187  178.992  [[177, 5], [157, 1], [140, 5], [112, 1], [36, 1]]
11188  179.008  [[177, 5], [157, 1], [140, 5], [112, 1], [36, 1]]

                                                     Ask
0                                                   None
1                                                   None
2                                                   None
3                                                   None
4                                                   None
...                                                  ...
11184  [[179, 8], [180, 3], [182, 2], [283, 4], [490,...
11185  [[179, 8], [180, 3], [182, 2], [283, 4], [490,...
11186  [[179, 8], [180, 3], [182, 2], [283, 4], [490,...
11187  [[179, 8], [180, 3], [182, 2], [283, 4], [490,...
11188  [[179, 8], [180, 3], [182, 2], [283, 4], [490,...

[11189 rows x 3 columns]
CPU times: user 3.61 s, sys: 57.4 ms, total: 3.67 s
Wall time: 5.09 s

### 1.2.2 Read the True LOB data
The format is like 's3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt'

In [40]:
%%time
#160037467 lines
print(sum(1 for line in sm.open('s3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt',"r",encoding='utf-8')))

160037467
CPU times: user 49.2 s, sys: 3.9 s, total: 53.1 s
Wall time: 1min 4s

In [27]:
def Read_LOB_Improved(source):
    LOB_subset_time = []
    LOB_subset_bid = []
    LOB_subset_ask = []
    time_i = -10000
    bid_i = -10000
    ask_i = -10000
    time_change_sign = False
    bid_change_sign = False
    ask_change_sign = False
    
    #Attention: errors = "ignore" for 2022-01-28
    with sm.open(source,"r",encoding="utf-8") as f:
        for i,line in enumerate(f):
            if i% 1000000 == 0:
                print(f"This is {i//1000000}th 1000000 row")
            if i //1000000 == 75:
                if i %1000 == 0:
                    print(i)
    
            #Time
            if line.strip() == '"time",':
                time_i = i 
                time_change_sign = True
                continue        
                
            if i == (time_i +1) and time_change_sign == True:
                time_number = re.findall(r"[\d]+[\.]?[\d]*",line)[0]
                #print(f"Time Number {time_number} Appended")
                time_change_sign = False
                LOB_subset_time.append(time_number)
                continue



            #Bid
            if line.strip() == '"bid",':
                bid_i = i
                bid_change_sign = True
                bid_string = ""
                continue
            if i == (bid_i + 1) and line.strip() == "[]" and bid_change_sign == True:
                #print("Bid None Appended")
                bid_change_sign = False
                LOB_subset_bid.append(None)
                continue          
            if i == (bid_i + 1) and line.strip() == "[" and bid_change_sign == True:
                bid_string += line.strip()
                continue
            elif line.strip() != "]" and bid_change_sign == True:
                bid_string += line.strip()
                continue
            elif line.strip() == "]" and bid_change_sign == True:
                bid_string += "]]"
                #Use for detect the fault line
                try:
                    #Use for 2022-01-14
                    LOB_subset_bid.append(ast.literal_eval(bid_string.strip().replace("M","").replace(" ","").replace(chr(0),"")))
                except ValueError:
                    print(f'This is {i}th row, {bid_string.strip().replace("M","").replace(" ","").replace(chr(0),"")} wrong')
                          
                except:
                    print(f'Something Wrong {i} rows')
                    
                    
                #print(f"Bid {bid_string} Appended")
                bid_change_sign = False
                continue

            #Ask
            if line.strip() == '"ask",':
                ask_i = i
                ask_change_sign = True
                ask_string = ""
                continue       
            if i == (ask_i + 1) and line.strip() == "[]" and ask_change_sign == True:
                LOB_subset_ask.append(None)
                #print("Ask None Appended")
                ask_change_sign = False
                continue       
            if i == (ask_i + 1) and line.strip() == "[" and ask_change_sign == True:
                ask_string += line.strip()
                continue
            elif line.strip() != "]" and ask_change_sign == True:
                ask_string += line.strip()
                continue
            elif line.strip() == "]" and ask_change_sign == True:
                ask_string += "]]"
                #2022-01-28
                try:
                    LOB_subset_ask.append(ast.literal_eval(ask_string.strip().replace("M","").replace(" ","").replace(chr(0),"")))
                except ValueError:
                    print(f'This is {i}th row, {ask_string.strip().replace("M","").replace(" ","").replace(chr(0),"")} wrong')
                          
                except:
                    print(f'Something Wrong {i} rows')
                                          
                #print(f"Ask {ask_string} Appended")
                ask_change_sign = False
                continue
        f.close()
        
        return [LOB_subset_time,LOB_subset_bid,LOB_subset_ask]
        
def Create_LOB_df_Improved(df_element,the_date):
    
    
    LOB_df = pd.DataFrame(df_element).T
    LOB_df['Date'] = the_date
    
    LOB_df = LOB_df.rename(columns={0: 'Time', 1: 'Bid',2: 'Ask'})
    LOB_df.to_csv(f"LOB_csv/{the_date}-LOB.csv")
    
    return LOB_df

Now let's test the 's3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt'

In [18]:
%%time
#Used to ammend ommisive file, like "2022-01-14": 
#This is 41th 1000000 row: source code string cannot contain null bytes


#Tst2022-01-14LOBs "MMMMMMMMMMMMMMMMMMMMMMMMMMMM" Wrong
df_2022_01_14 = Create_LOB_df_Improved(Read_LOB_Improved(
    "s3://project-b-data/proj-b/dataset-b01/Tst2022-01-14LOBs.txt"),"2022-01-14")

This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 41683188th row, [[187,1],[185,M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M M     2],[4,3]] wrong
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row

KeyboardInterrupt:

In [28]:
%%time
pd.read_csv("LOB_csv/2022-01-04-LOB.csv")

CPU times: user 2.26 s, sys: 195 ms, total: 2.46 s
Wall time: 2.46 s

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-01-04
1,1,0.016,NaN,NaN,2022-01-04
2,2,0.032,NaN,NaN,2022-01-04
3,3,0.048,NaN,NaN,2022-01-04
4,4,0.064,NaN,NaN,2022-01-04
...,...,...,...,...,...
1912495,1912495,30599.920,"[[220, 4], [211, 1], [175, 4], [170, 5], [161,...","[[236, 2], [411, 5], [436, 1], [659, 1], [725,...",2022-01-04
1912496,1912496,30599.936,"[[220, 4], [211, 1], [175, 4], [170, 5], [161,...","[[236, 2], [411, 5], [436, 1], [659, 1], [725,...",2022-01-04
1912497,1912497,30599.952,"[[220, 4], [211, 1], [175, 4], [170, 5], [161,...","[[236, 2], [411, 5], [436, 1], [659, 1], [725,...",2022-01-04
1912498,1912498,30599.968,"[[220, 4], [211, 1], [175, 4], [170, 5], [161,...","[[236, 2], [411, 5], [436, 1], [611, 1], [725,...",2022-01-04
1912499,1912499,30599.984,"[[220, 4], [211, 1], [175, 4], [170, 5], [161,...","[[236, 2], [411, 5], [436, 1], [611, 1], [725,...",2022-01-04

In [42]:
exact_date
exact_date[49:]

['2022-02-22',
 '2022-02-23',
 '2022-02-24',
 '2022-02-25',
 '2022-02-26',
 '2022-02-27',
 '2022-02-28',
 '2022-03-01',
 '2022-03-02',
 '2022-03-03',
 '2022-03-04',
 '2022-03-05',
 '2022-03-06',
 '2022-03-07',
 '2022-03-08',
 '2022-03-09',
 '2022-03-10',
 '2022-03-11',
 '2022-03-12',
 '2022-03-13',
 '2022-03-14',
 '2022-03-15',
 '2022-03-16',
 '2022-03-17',
 '2022-03-18',
 '2022-03-19',
 '2022-03-20',
 '2022-03-21',
 '2022-03-22',
 '2022-03-23',
 '2022-03-24',
 '2022-03-25',
 '2022-03-26',
 '2022-03-27',
 '2022-03-28',
 '2022-03-29',
 '2022-03-30',
 '2022-03-31',
 '2022-04-01',
 '2022-04-02',
 '2022-04-03',
 '2022-04-04',
 '2022-04-05',
 '2022-04-06',
 '2022-04-07',
 '2022-04-08',
 '2022-04-09',
 '2022-04-10',
 '2022-04-11',
 '2022-04-12',
 '2022-04-13',
 '2022-04-14',
 '2022-04-15',
 '2022-04-16',
 '2022-04-17',
 '2022-04-18',
 '2022-04-19',
 '2022-04-20',
 '2022-04-21',
 '2022-04-22',
 '2022-04-23',
 '2022-04-24',
 '2022-04-25',
 '2022-04-26',
 '2022-04-27',
 '2022-04-28',
 '2022-04-29']

In [22]:
import os
os.listdir("LOB_csv")

['2022-01-17-LOB.csv',
 '2022-01-19-LOB.csv',
 '2022-01-10-LOB.csv',
 '2022-01-13-LOB.csv',
 '2022-01-05-LOB.csv',
 '.ipynb_checkpoints',
 '2022-01-12-LOB.csv',
 '2022-01-07-LOB.csv',
 '2022-01-06-LOB.csv',
 '2022-01-18-LOB.csv',
 '2022-01-04-LOB.csv',
 '2022-01-11-LOB.csv']

In [ ]:


%%time
#"s3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt" format
for the_date in exact_date[49:]:
    t1 = time.time()
    LOB_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/Tst'+the_date+'LOBs.txt')
    

    try:
        print(f"Start Read {the_date} LOB file.")
        Create_LOB_df_Improved(Read_LOB_Improved(LOB_from_s3),the_date)
    except:
        print(f"There is no {the_date} LOB file.")
        continue
        
    t2 = time.time()
    print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

Start Read 2022-02-22 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row
The 2022-02-22 is finished. Elapsed time is 523.0489332675934 seconds.
Start Read 2022-02-23 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row
The 2022-02-23 is finished. Elapsed time is 517.1353623867035 seconds.
Start Read 2022-02-24 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row
The 2022-02-24 is finished. Elapsed time is 518.4403164386749 seconds.
Start Read 2022-02-25 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row
This is 159th 1000000 row
This is 160th 1000000 row
This is 161th 1000000 row
The 2022-02-25 is finished. Elapsed time is 523.3008823394775 seconds.
Start Read 2022-02-26 LOB file.
There is no 2022-02-26 LOB file.
Start Read 2022-02-27 LOB file.
There is no 2022-02-27 LOB file.
Start Read 2022-02-28 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row

In [39]:
Create_LOB_df_Improved(Read_LOB_Improved(
    "s3://project-b-data/proj-b/dataset-b01/Tst2022-04-29LOBs.txt"),"2022-04-29")

This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row

,Time,Bid,Ask,Date
0,0.0,None,None,2022-04-29
1,0.016,None,None,2022-04-29
2,0.032,None,None,2022-04-29
3,0.048,None,None,2022-04-29
4,0.064,None,None,2022-04-29
...,...,...,...,...
1912495,30599.92,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912496,30599.936,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912497,30599.952,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912498,30599.968,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912499,30599.984,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29

There isn't much space in sagemaker, so we need to store all the file in S3

In [32]:
############################################2022-01-14 wrong   i=41
############################################2022-01-28 wrong   i=155
############################################2022-02-04 wrong   i=117
############################################2022-03-03 wrong   i=75
############################################2022-03-07 no data

import boto3
s3 = boto3.Session().resource('s3')
key = 'proj-b/LOB_csv/2022-03-03-LOB.csv' # filepath in s3
doc = "LOB_csv/2022-03-03-LOB.csv"# your local file

s3.Bucket('project-b-data').Object(key).upload_file(doc)

In [40]:
%%time
#Manually check the number of rows and columns of csv in order to safely export.

pd.read_csv("LOB_csv/2022-04-29-LOB.csv")

CPU times: user 2.09 s, sys: 136 ms, total: 2.23 s
Wall time: 2.23 s

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-04-29
1,1,0.016,NaN,NaN,2022-04-29
2,2,0.032,NaN,NaN,2022-04-29
3,3,0.048,NaN,NaN,2022-04-29
4,4,0.064,NaN,NaN,2022-04-29
...,...,...,...,...,...
1912495,1912495,30599.920,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912496,1912496,30599.936,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912497,1912497,30599.952,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912498,1912498,30599.968,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29
1912499,1912499,30599.984,"[[133, 9], [132, 3], [121, 5], [93, 2], [64, 2...","[[158, 1], [329, 3], [418, 5], [479, 4], [502,...",2022-04-29

In [34]:
%%time
pd.read_csv('s3://{}/{}'.format(bucket,'proj-b/LOB_csv/2022-01-20-LOB.csv'))

CPU times: user 4.71 s, sys: 510 ms, total: 5.22 s
Wall time: 24.4 s

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-01-10
1,1,0.016,NaN,NaN,2022-01-10
2,2,0.032,NaN,NaN,2022-01-10
3,3,0.048,NaN,NaN,2022-01-10
4,4,0.064,NaN,NaN,2022-01-10
...,...,...,...,...,...
1912495,1912495,30599.920,"[[200, 3], [174, 5], [169, 1], [138, 2], [116,...","[[204, 5], [205, 3], [207, 5], [209, 2], [214,...",2022-01-10
1912496,1912496,30599.936,"[[200, 3], [174, 5], [169, 1], [138, 2], [116,...","[[204, 5], [205, 3], [207, 5], [209, 2], [214,...",2022-01-10
1912497,1912497,30599.952,"[[200, 3], [174, 5], [169, 1], [138, 2], [116,...","[[204, 5], [205, 3], [207, 5], [209, 2], [214,...",2022-01-10
1912498,1912498,30599.968,"[[200, 3], [174, 5], [169, 1], [138, 2], [116,...","[[204, 5], [205, 3], [207, 5], [209, 2], [214,...",2022-01-10
1912499,1912499,30599.984,"[[200, 3], [174, 5], [169, 1], [138, 2], [116,...","[[204, 5], [205, 3], [207, 5], [209, 2], [214,...",2022-01-10

In [82]:
%%time
pd.read_csv('s3://project-b-data/proj-b/Tape_csv/Full_tape.csv')

CPU times: user 11.2 s, sys: 1.96 s, total: 13.2 s
Wall time: 34.1 s

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10
0,0,Tst2022-01-04,Exch0Lit,8.192,203,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 203,'qty': 2,'party1': 'S26','party2': 'B24'}
1,1,Tst2022-01-04,Exch0Lit,8.192,199,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 199,'qty': 3,'party1': 'S26','party2': 'B08'}
2,2,Tst2022-01-04,Exch0Lit,10.336,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.336,'price': 196,'qty': 3,'party1': 'S06','party2': 'B07'}
3,3,Tst2022-01-04,Exch0Lit,10.672,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.672,'price': 196,'qty': 4,'party1': 'S01','party2': 'B01'}
4,4,Tst2022-01-04,Exch0Lit,11.040,201,{'pool_id': 'Exch0Lit','type': 'Trade','time': 11.04,'price': 201,'qty': 1,'party1': 'S12','party2': 'B31'}
...,...,...,...,...,...,...,...,...,...,...,...,...
5230359,64888,Tst2022-04-29,Exch0Lit,30599.376,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.376,'price': 134,'qty': 1,'party1': 'S21','party2': 'B07'}
5230360,64889,Tst2022-04-29,Exch0Lit,30599.520,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.52,'price': 134,'qty': 1,'party1': 'S03','party2': 'B07'}
5230361,64890,Tst2022-04-29,Exch0Lit,30599.584,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.584,'price': 134,'qty': 1,'party1': 'S28','party2': 'B01'}
5230362,64891,Tst2022-04-29,Exch0Lit,30599.776,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 134,'qty': 3,'party1': 'S04','party2': 'B01'}
5230363,64892,Tst2022-04-29,Exch0Lit,30599.776,133,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 133,'qty': 1,'party1': 'S04','party2': 'B19'}

In [83]:
%%time
pd.read_csv("Tape_csv/Full_tape.csv")

CPU times: user 7.45 s, sys: 638 ms, total: 8.09 s
Wall time: 8.61 s

,Unnamed: 0,0,1,2,3,4,5,6,7,8,9,10
0,0,Tst2022-01-04,Exch0Lit,8.192,203,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 203,'qty': 2,'party1': 'S26','party2': 'B24'}
1,1,Tst2022-01-04,Exch0Lit,8.192,199,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.192,'price': 199,'qty': 3,'party1': 'S26','party2': 'B08'}
2,2,Tst2022-01-04,Exch0Lit,10.336,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.336,'price': 196,'qty': 3,'party1': 'S06','party2': 'B07'}
3,3,Tst2022-01-04,Exch0Lit,10.672,196,{'pool_id': 'Exch0Lit','type': 'Trade','time': 10.672,'price': 196,'qty': 4,'party1': 'S01','party2': 'B01'}
4,4,Tst2022-01-04,Exch0Lit,11.040,201,{'pool_id': 'Exch0Lit','type': 'Trade','time': 11.04,'price': 201,'qty': 1,'party1': 'S12','party2': 'B31'}
...,...,...,...,...,...,...,...,...,...,...,...,...
5230359,64888,Tst2022-04-29,Exch0Lit,30599.376,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.376,'price': 134,'qty': 1,'party1': 'S21','party2': 'B07'}
5230360,64889,Tst2022-04-29,Exch0Lit,30599.520,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.52,'price': 134,'qty': 1,'party1': 'S03','party2': 'B07'}
5230361,64890,Tst2022-04-29,Exch0Lit,30599.584,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.584,'price': 134,'qty': 1,'party1': 'S28','party2': 'B01'}
5230362,64891,Tst2022-04-29,Exch0Lit,30599.776,134,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 134,'qty': 3,'party1': 'S04','party2': 'B01'}
5230363,64892,Tst2022-04-29,Exch0Lit,30599.776,133,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.776,'price': 133,'qty': 1,'party1': 'S04','party2': 'B19'}

### Dealing with wrong data

In [28]:
############################################2022-01-14 wrong   i=41
#M problem and chr(0) at 41683188 line, but then only have 1912492 row of csv


############################################2022-01-28 wrong   i=155
#UnicodeDecodeError: 'utf-8' codec can't decode byte 0x91 in position 8107: invalid start byte
#Approximately 155491830 line
# unicode_escape and utf-8 error = "ignore"

#1912492 rows

############################################2022-02-04 wrong   i=117
#Memory Error? No
#1912496 rows


############################################2022-03-03 wrong   i=75
#Nothing wrong!
#1912500 rows



############################################2022-03-07 no data
Create_LOB_df_Improved(Read_LOB_Improved(
    "s3://project-b-data/proj-b/dataset-b01/Tst2022-03-03LOBs.txt"),"2022-03-03")

This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
75000000
75001000
75002000
75003000
75004000
75005000
75006000
75007000
75008000
75009000
75010000
75011000
75012000
75013000
75014000
75015000
75016000
75017000
75018000
75019000
75020000
75021000
75022000
75023000
75024000
75025000
75026000
75027000
75028000
75029000
75030000
75031000
75032000
75033000
75034000
75035000
75036000
75037000
75038000
75039000
75040000
75041000
75042000
75043000
75044000
75045000
75046000
75047000
75048000
75049000
75050000
75051000
75052000
75053000
75054000
75055000
75056000
75057000
75058000
75059000
75060000
75061000
75062000
75063000
75064000
75065000
75066000
75067000
75068000
75069000
75070000
75071000
75072000
75073000
75074000
75075000
75076000
75077000
75078000
75079000
75080000
75081000
75082000
75083000
75084000
75085000
75086000
75087000
75088000
75089000
75090000
75091000
75092000
75093000
75094000
75095000
75096000
75097000
75098000
75099000
75100000
75101000
75102000
75103000
75104000
75105000
75106000
75107000
75108000
75109000
75110000
75111000
75112000
75113000
75114000
75115000
75116000
75117000
75118000
75119000
75120000
75121000
75122000
75123000
75124000
75125000
75126000
75127000
75128000
75129000
75130000
75131000
75132000
75133000
75134000
75135000
75136000
75137000
75138000
75139000
75140000
75141000
75142000
75143000
75144000
75145000
75146000
75147000
75148000
75149000
75150000
75151000
75152000
75153000
75154000
75155000
75156000
75157000
75158000
75159000
75160000
75161000
75162000
75163000
75164000
75165000
75166000
75167000
75168000
75169000
75170000
75171000
75172000
75173000
75174000
75175000
75176000
75177000
75178000
75179000
75180000
75181000
75182000
75183000
75184000
75185000
75186000
75187000
75188000
75189000
75190000
75191000
75192000
75193000
75194000
75195000
75196000
75197000
75198000
75199000
75200000
75201000
75202000
75203000
75204000
75205000
75206000
75207000
75208000
75209000
75210000
75211000
75212000
75213000
75214000
75215000
75216000
75217000
75218000
75219000
75220000
75221000
75222000
75223000
75224000
75225000
75226000
75227000
75228000
75229000
75230000
75231000
75232000
75233000
75234000
75235000
75236000
75237000
75238000
75239000
75240000
75241000
75242000
75243000
75244000
75245000
75246000
75247000
75248000
75249000
75250000
75251000
75252000
75253000
75254000
75255000
75256000
75257000
75258000
75259000
75260000
75261000
75262000
75263000
75264000
75265000
75266000
75267000
75268000
75269000
75270000
75271000
75272000
75273000
75274000
75275000
75276000
75277000
75278000
75279000
75280000
75281000
75282000
75283000
75284000
75285000
75286000
75287000
75288000
75289000
75290000
75291000
75292000
75293000
75294000
75295000
75296000
75297000
75298000
75299000
75300000
75301000
75302000
75303000
75304000
75305000
75306000
75307000
75308000
75309000
75310000
75311000
75312000
75313000
75314000
75315000
75316000
75317000
75318000
75319000
75320000
75321000
75322000
75323000
75324000
75325000
75326000
75327000
75328000
75329000
75330000
75331000
75332000
75333000
75334000
75335000
75336000
75337000
75338000
75339000
75340000
75341000
75342000
75343000
75344000
75345000
75346000
75347000
75348000
75349000
75350000
75351000
75352000
75353000
75354000
75355000
75356000
75357000
75358000
75359000
75360000
75361000
75362000
75363000
75364000
75365000
75366000
75367000
75368000
75369000
75370000
75371000
75372000
75373000
75374000
75375000
75376000
75377000
75378000
75379000
75380000
75381000
75382000
75383000
75384000
75385000
75386000
75387000
75388000
75389000
75390000
75391000
75392000
75393000
75394000
75395000
75396000
75397000
75398000
75399000
75400000
75401000
75402000
75403000
75404000
75405000
75406000
75407000
75408000
75409000
75410000
75411000
75412000
75413000
75414000
75415000
75416000
75417000
75418000
75419000
75420000
75421000
75422000
75423000
75424000
75425000
75426000
75427000
75428000
75429000
75430000
75431000
75432000
75433000
75434000
75435000
75436000
75437000
75438000
75439000
75440000
75441000
75442000
75443000
75444000
75445000
75446000
75447000
75448000
75449000
75450000
75451000
75452000
75453000
75454000
75455000
75456000
75457000
75458000
75459000
75460000
75461000
75462000
75463000
75464000
75465000
75466000
75467000
75468000
75469000
75470000
75471000
75472000
75473000
75474000
75475000
75476000
75477000
75478000
75479000
75480000
75481000
75482000
75483000
75484000
75485000
75486000
75487000
75488000
75489000
75490000
75491000
75492000
75493000
75494000
75495000
75496000
75497000
75498000
75499000
75500000
75501000
75502000
75503000
75504000
75505000
75506000
75507000
75508000
75509000
75510000
75511000
75512000
75513000
75514000
75515000
75516000
75517000
75518000
75519000
75520000
75521000
75522000
75523000
75524000
75525000
75526000
75527000
75528000
75529000
75530000
75531000
75532000
75533000
75534000
75535000
75536000
75537000
75538000
75539000
75540000
75541000
75542000
75543000
75544000
75545000
75546000
75547000
75548000
75549000
75550000
75551000
75552000
75553000
75554000
75555000
75556000
75557000
75558000
75559000
75560000
75561000
75562000
75563000
75564000
75565000
75566000
75567000
75568000
75569000
75570000
75571000
75572000
75573000
75574000
75575000
75576000
75577000
75578000
75579000
75580000
75581000
75582000
75583000
75584000
75585000
75586000
75587000
75588000
75589000
75590000
75591000
75592000
75593000
75594000
75595000
75596000
75597000
75598000
75599000
75600000
75601000
75602000
75603000
75604000
75605000
75606000
75607000
75608000
75609000
75610000
75611000
75612000
75613000
75614000
75615000
75616000
75617000
75618000
75619000
75620000
75621000
75622000
75623000
75624000
75625000
75626000
75627000
75628000
75629000
75630000
75631000
75632000
75633000
75634000
75635000
75636000
75637000
75638000
75639000
75640000
75641000
75642000
75643000
75644000
75645000
75646000
75647000
75648000
75649000
75650000
75651000
75652000
75653000
75654000
75655000
75656000
75657000
75658000
75659000
75660000
75661000
75662000
75663000
75664000
75665000
75666000
75667000
75668000
75669000
75670000
75671000
75672000
75673000
75674000
75675000
75676000
75677000
75678000
75679000
75680000
75681000
75682000
75683000
75684000
75685000
75686000
75687000
75688000
75689000
75690000
75691000
75692000
75693000
75694000
75695000
75696000
75697000
75698000
75699000
75700000
75701000
75702000
75703000
75704000
75705000
75706000
75707000
75708000
75709000
75710000
75711000
75712000
75713000
75714000
75715000
75716000
75717000
75718000
75719000
75720000
75721000
75722000
75723000
75724000
75725000
75726000
75727000
75728000
75729000
75730000
75731000
75732000
75733000
75734000
75735000
75736000
75737000
75738000
75739000
75740000
75741000
75742000
75743000
75744000
75745000
75746000
75747000
75748000
75749000
75750000
75751000
75752000
75753000
75754000
75755000
75756000
75757000
75758000
75759000
75760000
75761000
75762000
75763000
75764000
75765000
75766000
75767000
75768000
75769000
75770000
75771000
75772000
75773000
75774000
75775000
75776000
75777000
75778000
75779000
75780000
75781000
75782000
75783000
75784000
75785000
75786000
75787000
75788000
75789000
75790000
75791000
75792000
75793000
75794000
75795000
75796000
75797000
75798000
75799000
75800000
75801000
75802000
75803000
75804000
75805000
75806000
75807000
75808000
75809000
75810000
75811000
75812000
75813000
75814000
75815000
75816000
75817000
75818000
75819000
75820000
75821000
75822000
75823000
75824000
75825000
75826000
75827000
75828000
75829000
75830000
75831000
75832000
75833000
75834000
75835000
75836000
75837000
75838000
75839000
75840000
75841000
75842000
75843000
75844000
75845000
75846000
75847000
75848000
75849000
75850000
75851000
75852000
75853000
75854000
75855000
75856000
75857000
75858000
75859000
75860000
75861000
75862000
75863000
75864000
75865000
75866000
75867000
75868000
75869000
75870000
75871000
75872000
75873000
75874000
75875000
75876000
75877000
75878000
75879000
75880000
75881000
75882000
75883000
75884000
75885000
75886000
75887000
75888000
75889000
75890000
75891000
75892000
75893000
75894000
75895000
75896000
75897000
75898000
75899000
75900000
75901000
75902000
75903000
75904000
75905000
75906000
75907000
75908000
75909000
75910000
75911000
75912000
75913000
75914000
75915000
75916000
75917000
75918000
75919000
75920000
75921000
75922000
75923000
75924000
75925000
75926000
75927000
75928000
75929000
75930000
75931000
75932000
75933000
75934000
75935000
75936000
75937000
75938000
75939000
75940000
75941000
75942000
75943000
75944000
75945000
75946000
75947000
75948000
75949000
75950000
75951000
75952000
75953000
75954000
75955000
75956000
75957000
75958000
75959000
75960000
75961000
75962000
75963000
75964000
75965000
75966000
75967000
75968000
75969000
75970000
75971000
75972000
75973000
75974000
75975000
75976000
75977000
75978000
75979000
75980000
75981000
75982000
75983000
75984000
75985000
75986000
75987000
75988000
75989000
75990000
75991000
75992000
75993000
75994000
75995000
75996000
75997000
75998000
75999000
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row

,Time,Bid,Ask,Date
0,0.0,None,None,2022-03-03
1,0.016,None,None,2022-03-03
2,0.032,None,None,2022-03-03
3,0.048,None,None,2022-03-03
4,0.064,None,None,2022-03-03
...,...,...,...,...
1912495,30599.92,"[[197, 5], [183, 2], [181, 1], [166, 3], [154,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912496,30599.936,"[[197, 5], [183, 2], [181, 1], [166, 3], [154,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912497,30599.952,"[[197, 5], [183, 2], [181, 1], [154, 4], [138,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912498,30599.968,"[[197, 5], [183, 2], [181, 1], [154, 4], [138,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912499,30599.984,"[[197, 5], [183, 2], [181, 1], [154, 4], [138,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03

In [26]:
#Detect what's happening in the wrong place
#Tst2022-01-28LOBs
with sm.open('s3://project-b-data/proj-b/dataset-b01/Tst2022-01-28LOBs.txt',
             "r",encoding = "unicode_escape") as f:
    wrong_i = 155491800
    for i,line in enumerate(f):        
        if i% 1000000 == 0:
                print(f"This is {i//1000000}th 1000000 row")
        
        
        #41683188
        #155491000
        if i >= wrong_i and i <= wrong_i+1000:
            #print(line.strip().replace("M","").replace(" ",""))
            print(line.strip())
            
            
            
    f.close()

This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.352,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
204,
3
],
[
205,
5
],
[
206,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
563,
2
],
[
 ÄðØ¨J@:-4',¤­ÐÜÚD^\qV%ü	GMÊ4)ÑO¹É¡?ËAÜoèÕîqÁó?o{Å{æ¸\½ÛÒfÖÆZ}Å>Òë¾ËÊiË©aÈãT¸ ð®iX¿½í'ØßUHú|úây½×1ã³{cçgbDoidùNÊ©_ë|6îØÿG«g/z ç|ö	a ¯´ëã»5Ò ¶ÿS ÊEï*cXPp¹ØÖÝZÞÿålðï»¢Ê««#VÃ©FÄ>ö=ü%;OÙg¤2V¹vè¶Nd|«Ü¶o¤Å)ouBÕ1|?Þ+ÃÒÚó¾·þ<2søéëcú¸e-°ØèðV«NÜä}6dN¡ÚµâÔÚÂ?äíÕñ;¦Þ¼¿±ºÒ/Akò)ór*JÅ¦¸/d[
s¹û®q
ùó«õÍÓUtcô0øÜúà4ÄÌX·· 6&ÖÑge7¼äWëÝsåÒ®KE}`¯¼ÛÉë¶`ÉöRß³¹)GÌ6ÝEþ»öB:l³f*;ÅfÆ#°eÂÉH©À#ªÛ\IE¼òhÙgI¯d8áßÅn9;t0îsÌÕ± r ÎÐ ô[[ùËit¯¶³]yöø#àÕí©0çkH_zE;Ä4tÈÉ{qñ?iAÔ_üfiÓ+eC`±Äf%|íw
ÉÉ(hhÁØh)Øñ£Í@ò,U¯Ã*â°©
Ý$44-«g%ðVT¸éYb³â¶N@þ 9_¬þ»3ÇFù(`Í5$1ÊÀ¶Qyyi¥Ãû^¥³H®Õ©/é9d<?¤rÏª}ÖOëcq0
¹Àôyáp?î«½èâv	£ÊvZ§q%[dÏì©ë_å¯½h×j×Jì¶
'ÉÓ ¨À`u	­­m÷5aã¼ëÄ²ÿ¥eÎ2Y7$òâ÷ k+8P*WF|ß©*©¯z^+ôìòéa#f¡¾Wòbó]Ó£¢Âdâ×ÜÞòTÝüßº9¾Ó=Àwç	ø=MDJ°ù;Ç¶*+ ùÔhî¾§°ñcV÷ë£dÞjçnÕå$Cs ÛIÄ¬·*=%2ÚàyW±ÀÄÞKõ=ÁÞ7nÃ£´Ø×r¾W!måª×\ÆRo	60O;y'ÍFc£û£YæÔÃÔ
ÅØ&ÑBG9un²ô
Ó+E×òæ¥ÆëtªBïlØ]ËËç,r07UT<ë·Û¢%°xoëUñít½ÉKOÚÙìWF*]³w«	î=S§`Ú-ÆH
R¤ül¢òËs:8H?´Www¤IU<z±81d¢Ð³wûQÎXú8^âªc¿5ãÃÀLïs(¹BHü¾¢+aìÅã?1ôPÞ&¿ÉÕ4vÂ/;;&r´IØÖÂØ?®3{ÞæS.:Ey1ñ8WpØIÏÁÄü¼%%³Ó¯ýÑäªä6±êeñ¯S|ðk1
é
¾(@(S$ê1Ý-­cÖÎ¢ä_¢xÌÈÉÈêy8Å_Wg­èCÈ0GËVøO,ÈßíÂ-»lÔoüÐ.%´±£(ñ,%
öÕÙ|6µTy"{1/µÁ/¶lO KìI8~Ä¯X:¨nõk®¡RíÉ¨ßTC³Y[P`ë/ºR î0w×Ó!àITåU©U«Ê£Ãt°ùr¾¯+$µ¸AKwÙáwn·ÀhS¤wk¬¯¬C=¥<:õÍÎAYçMp3¨H×Ö¯®è+I{=ÔÛ,î´j¹Sü7ß¿~?Æy9§7T,ïÕF1¬Üy@×Çt¼n[¿mØWü[öFtöoy+°X«'ùWìbåGÇÁ7{,¸÷xüî ÓNfç²ê¶¤Î#«dç\Tqöv,W²ÁÎ|þ\ªEÒÓCZáR-PQFÇíÃûÒ¬°ù}t/x/`)5m'<GfçEEæëÓÍ_-q=¤Üo^¤FN·÷Ó¸.ÎÌ`\ëå£PÖÌµÉôù)Eòâåä>?ÿg!¿ûCq*L¶ähÀIÑ}'z@Znl9dãûØø(óNûåäy²ÈI[}é(QÆ51ÔÌ<úóSáÊ±#<ga'_S×÷Ú+i'±JUñák½sºUs#RêÑékVß
].òòºwOAtí=ië÷øVKK]ÖÓµÁe_î0I³U¦cß÷­wäë©ÙúïË®%T"Ä-sýÇpá}þÜ·µë<M.Ê`Ë[/¯vØ'(ñeE¹#émïl¢.þ¾&ë°hg:q÷$hl:²Ì$ë}N&¥ÕesÅDÕ¯CPªUçUábÊÅû·~uy»vgqÿ¶æ19I*}-«1»|&³Ô+zèâ±XçÂð©û-¾ajì7X7¹ßV ?(of}{·a¸»ñ£TñÙa£áCW·ËNºä]¿Ú¢ªÓíúØ MÐ
ÁSÈhk ã©h²[ã&V\ùëÚû&£¶tóûoÆâ\m!FW¾lÈØ½:\¶Å÷øYôæÌIqÕáí$o_Nöz5j³d©å¶õ
5èùÊªwE¤nIdåì
<?äÛâ5/ç1Ï>~ÜÉjþÇf±ÔzµâÝ£[n;y?âO?ô]9Zmáåû	L]h¤!þÌ³1Ã5üWu>bï¨L>YçÛ4oD_ù}3¥$ô D.
;§ ÌÑíÈã£?Ë8Ê©÷5f²åD4þÄPRuqÄ3'©)m#«s'
NÇ%§#|qå_ò³Íµ÷+ê{Ü­ÎûhÈÖ,Úî*ÂN9¥lÜZÃË"¶ëw-»>Lax%DÁZÆ`1óü\·g0ü $vK}©/EûXyÚ»Q¾¡í9Í!.}lÝ$ì­ÓrrÌôÈ2PWÓÑ×íYi:æ[l.èìÖ7ûY^?¼SqüTÐ+%üñ	¹!
-¡ÔL2tÂ2YT¢hôâìû:ôÉáðëPzO1ñÐ>>@m²pEù(A;H]<úéQmjoþè\W1QFb^ºcXÈêÝ|8¿Á?shwIë¥¼"ëñV¶Ñ(åáÂ¬2¥Lpaylx×î0¼g3o
ccl§ØYÕÔ	mþ¦7^?Â~¡þ¹i»7!gP©Lâ6	òègí»S½½b|Òí	§ÜÂýÄ@{y¼ÊR%$=¹Ò]VÑ`9¯?,NËõÚâÏ0©è¶åqÎ­Æ¶3õeï*¬2+èMÿ6`òµTÓJÜïNÕ=r,I{ð¸#:l<üBæÌF/>KSÕdàJÛQX[TLû<ö`IÝ¨ëý¾LÑÄ#ã~à{gf¼mmþ¦%dJoËC@ÄxÂ£jâ°ù.®ÍZ7èx¦¦N
_ù1_jíLà®ÁñL>w)uwîFÛ Öp	¬¬O¯¨ÿ.øÄð©¬_eV¡¥$ÝÓ¬«¾ie=Â·?)ÄÒ'æi>Ù÷?±|ÁUJZ+eÝNµøMåã'=¶¸°µâ~C¥ÖRdÈÅîTmlmúM¾òÜ:éOK[Äó+ý~Ü÷ä¹£äyDmß#¤ tâ2þZpD¨EÚ^h^8,²ÿbþlªÔæü«ÔÀ+~4pS8<-íLÍëQ®5º¯SüÕª56ðV5t¥×àí0È K»Ó`"cýTð=½âòÝ]½E]èÕÝù?ÜçÚ4³I³ß~{dþï±wÃü8t1Ç»m\XIÖC¿Ñ{ôªpÝýùTÓV³j×ÏA-|»ÑpXÃa:RhúJzm¨ÂSËº$Älñ%N*(Å/ôÿ"õîÃRw­£¹Ç?<c¾¤ÝÀbË}A÷C=2òY?qô%ö«3-Z^ê÷vÙ+[32d&#fC'éæõWé©Nvä,}³Tm¡çCO¯­þb^Mqn<úû/>í¬¬$¬· Íózy~QÆí&Xß»Ð_ÄcR³=±ñ>o¾»Ê­8½ÚÀbbÎ^}ÈOÏ÷ª6«6Ö¸£?ÿw}Và«-ÍGhõg?vúæT.ÉvÎêû7h¯
éry^-&$?Jö÷©t@#:äRV·üÓºR.:=ÀþjqØ¬Ê-eBÑTªùÁóKJ=/aûW÷7¯ÃÎ MFl¼bl%qbëXúàþjC<6Ìuz+QbÝBÉP:ñ®ÿ´ÎUlC.çLÄä*Ñø³µ³Ý ø}½9Ußÿ\aõ	kc±+O§½-¿ß£
Ãr&©03Ü]ÆQW±¥­B&}WÇO4Õþ¹kWµwÅï}ÓiÎ²Æ¸¹Ò.ÞóÔ?3õ_@ù¨JÐ|o7o¢Þø_ã÷-.ùqWznáKìÙGòîbbÞ:Cþ¬÷1½w¤ñOÓ?pØ'î×~4©
a~)´¤ü|¨&¿ÇØ¸æc¸ìÚñ²:ÿgw:K¦ä±æwqQ3ß WcÐu²êÇþ£o±9½KãS,áe0:j"QUxo9i°::2wgFûÊì4äA1@ëÈAr#ë)dHj+|Ôa× Ï@fâx[Z>F¿a,$ÜØîGÒüm`07ÇFK¡Ä,éº¾KTsÈ>=Û¬Ú§"£«àÝMO¹FÛ*58gu4éôæl)îuqÖÃuÚºÒ7Ìh¼ÿ4è<äòTØåg8ø·~Z´ØxÚÙ¬Q?×$æSÞyìïa]Ù60ó_à*ç_ú¼3[ádl' ÝV¿§Ðj¬-aôWÐ¸l¼XáfÙD+â+õô}Pß>Uxe d¯ä(;Õ©ùá*ý9]gî|.¶·qnòá^ ¿Îz¼h½°âèN~<¥ö1Çh´áGÜW8Äf¤Uø8ù£¡§bÆíÄ)¥÷Gz:Ñµ×Â98 zB3·9sÄåÄå\×'ËÌÊý]gã£·çO÷¿úWÂ;D
ïr2OVWbHäâµØù±â'
óöÜÆ@HZìþÔÅ)òéêmú¾¬ÿéÇÆ¤Å|wsèù5³xÍG¼Úä>½ ïµZíý\YÌ3%5vÙ?¸Ù÷ì3sSöãmÈÙ^í¶[`/¨<z'_B¿µ
`ÝeøvpØl,
>.ü8ºBñ¸r4ü«&fZwéGic·ä/Ð <b""©Õ³§¶]O<pÓbÌåÅñA§ÑtaÔÞ/-@mÞ×KC2KegU^Ã).vÏâåù|k~¸OÔ¼ÖãcÑRÁ?a¹/1¦xGM£T·aJèû!¦TqfJd¤]Å³3àñ?ÎÄé¸ã¿mlîsÊ1ÂäX%7s5÷&Ç;SÉ¥k#fæ9Ë9G!g¥û%	Éruyzßó?ü~ßãó}¿_¯ljÉS£«fííE|¤»ØÐ_î *Ôõñ£å"O4AvË§ËÝ8¥}vä¡i¦²©?RÒZ +C³þµÐÎ_@`£7g w08]eØ ãËzo£joÉYÞ®HKVUbË;¾ý
bfì?^©zù¾_9ûAêså0-òÆÕºkÞ!­}û:J`gîÆPÔÀ'3bÎÇ¡£¸c¬4³V4»ìtèúâÀß¨"®ÃW.ßy8¶_^udþ«ÚÊX}_êÞÙÝnyêXÔnW¦q)T>µRùé\Mæ3»37v]÷t{ç¾J7Î\F53.-ÓSl¹¢Ù÷ß¼£JH¿ddsÂÍ9NÈÕ MMïtT=é2VDC¨	ËgÏgbIx<2$ÂÂ­¥ÀÅ^õ_ÿ29ÆAUÆróöÙÓ8icy²kq*ò.1ñCL_Åöp-ÂnÇ§·ÛK)s²ÐãôG|i­ó¬¯¼%øGÇ«¦Fn*ôõ­±ñ¬9Þ±kI®¨ê
¹©)G³¬¶FmÛv;ævÉG_ó3æ0JàÓwp¸¡ZÕÓ)VÙ:#P|[Õûc\îME_05/-}o{¯JÔvÍ¯T_ÃXÀ/LËöMk¨)eÝÁ <²Ü'%ÿ­m¬á+@ßß÷Ó¯´_F8+HÍûUt ª¢"ÛÎõOñÁ±ÃcP$ÇÙf#<;¡AaªvÝ¶ÕÉVÆ%,dS»'±¾öJó±o²Or=Aª¬áÎ.¿¬ÖÐ6ä~±'ö7.ÜH8¦¹ñYm3Å»i´r}ë	²eKÊv¢ÊUTEù®iÂ,+¿Ô«2CßE
ÐuÔ~Óö×S= qëv.0,¨f¥z;`3[Lccé£ÔÌ©pÇÉìC5H$Fp[Ëº^â9¯Ln l>Üxv&uº´>ûßwñXá#¶%ÖÉÊ
ÛÛ1x{Û!bádü¥mà´e÷7°>õï¯Ñ&òºûvÎ6®éÁq½û"yLtbúqKüfÊMdCð£N²bH#zM3S
Ù¯ü '=tôCßB3·Åÿ|^­¨þ¡þéá5Ó½PiÃqè õÛ6A%sûçÛàØ¶f^¯ö4X¡Ê=¶ñaÝXTÒù¸ráp;¶Õõøg,¹ZÚq4/4¥s\E$/í"ßãÂ¬¹ùgzl°r¤:
{fþÆLNâä
Ø+az%©å]¸ÒfçYúñÓ£+Øzm#wâBl¥7®ë_XltÑ{Þúï¤m¬>v,jÐûÙÁ¬ EÏc²m½Ó"ô
{øh.¹´c¢EÐÀ:V5ü´@RrFg\÷aH´9ÃlË9òÅ^×Zh\fÐºa Ó§kªc1©^gzâ pFíêòþ>ÓUeþpß	¢¢#5LÂmçp´Zù_åõayöqmH3-	KÉMÇI)EÂÚ4ÐnÛSµçseÉÖèô?Îús#×ÊV?&OÄ|®Jx;rÑSÑ¦F³ëeRÑD·yt. [ûÞý×iöÉ~í!f(ñ`²Ê8@
%>Dî
F¬ÅÌ~²jMFCú(]e3tåc*9:T7R©B!Ï.¤?*jÙ²½W¦¢Kêb R),B'¾©ÌÇGÖnõ¶ RÚººu'Äò!|0c­®Äz
ÒXõ8Sj§Ûº×w^ÚBÁuûûúªdpACËB<¬ÙgÈ¼¥6QãIø#ÿ	!^Û«(¹ß¹é},þApbôè2½hqÍÖvçõ¨Q+ÍÒÙ¼<ÖÂºÙïoyê½»ü2¹Äõä3¿´ÙýK÷4ËÓ/`¦÷ñ.ÞÕêiýÆ|f¨XL!¾eÆxùâFC~EÜNÍðª:
v¯qàQkÍëÙ{ÝïÛ#<OJÓçïÎÏs×ìÅ+ìh!õ
uxh}³TkM<2 fâ_/:k»ï<È/ßá:INøÍ_Ò(VT ã¡7ËÓkGZÈ3Ç¤¥kôÊnºI´)Uep÷íFþLÒ «¦v¨ñO6¯ø|>ðFR¦T¸¤)6ï©
0§Rº5ùd(¦zßëÞ]è[³åG~£±¶±pt¡Ð9QcÏàº×ý-{@B®¹øÇáFgµo0öìøÁHK0Õiö¹N×dü^\éýYÃùÎÙÅS¥v/Ë¸YH]Èím:éYÑX/ª°=®¡wâìÝ-»w®¹*q÷k5óÜ9¼÷à?ÿC6qXHºo%Ç^«â¿Ú¨­}%bU³9G'.xåeÒo»N²ß'-ÛK·¹­Õ
Ó:é¥·O)amÚD9z´gßÑJÚËÚ½1÷¿PJ{-úºvãWþiîl¤·ÚãÒÖìïçã&Ö&-&õB©»Þ`iV'++Å÷¡&Z}%7ßÎ ^LA
E£ÕÃ®Ë²gÃllqålÁhÿ·¯à(èÌDShä~©Ê
}#¢G¢5 .ô¹s8Æ¼å`ÿa~üB:KÏ±T9"ÿ9*km	`r_Öã×d+ %ÏMJ»ÊÎF?4	#U5¯47Ú¼?ò¥ÅÎ:zÿr}XâäØext¾6ìõ  µvK´ØJÖ¥B,,o®¾'bVSî·Q{}IÌ¢Ô¤¤CÿéL_w8R
h	ÛúMk6hÏ,"X@øÅìpkÕMY¬±LB{"&¢]EDÕñÓð½16À'tæÛª$CAÜL·z½`7§bðP4kõûÿ)ªáä!Jjav[¿{ì'£V³×]:Nù8¥û»Þ	A¶3­øÄÃÊSÏxÌDi/ fòKÑÉ¼âåµÓÍÆGjäC$D¼âR«r0ïÝÂm/Vì=CÁI9ÊzjìhL³D8w*fJ\Eý
Æ9¥]ò*«éL2mõtÖ}É[{áiLÀvÓö|ªbq*$8Ùå¿,9WeBúFGuUeU{±ìb¥7/Þ·AÕ{îDsHa±OlLÖJÛJ©¸þÔ~VºgY[vwÅBzæ~Á¾ÅÙº÷:Ú^_¾ß¸ÁÓ¢ýºÇï¨þ0vIáçTe}cBaë]ÛT°ð9!+Å´´Ù?¢¾þûKjÙtBªï¯ñ{\Wx[ÐQ	I_FÃ÷Nê<>/:ÔÞzÄÐEËêj³ºm]etV5¹§Ù 5.ÐY÷yê
-p0:CÐòÃ(¬`Oï0óºil±ÿº*Ä/#Áè!´&aÑ¨¥RXùíXlkµ6"n¢+v¨>1yrvÖ ö*¬ß¤«òßE	ìÞJ!Ú?X]­±I¸¢R©WS}ÃU
eW/oO®«È.\M-*¥Ô¡¹nGy%-ãïCõúø8H«YÕ±¸ÂWýÌey¿ÎO8òx§8½[+%Õ×Hu¶>Ì¯0f-zçÅqJ®þ®+E4Wf¥s9ËþÓzaX1ÆË³zeð-6ÿ>íÆÏÊ'<«Ø2XÐ­Ù¯öåálF£kLÖÞ#MÅÅix±2°&	þNbIþÛ$­¢`Õzzµ ãÐvçN¾¿y¯heA£*áÞü¨(DÌ$ÑñkTÓ56O? ê¬*Z ,ä	÷cÞ¾AB§YTJhìtZP&ç¥¿pèM¶þí&ÚäWAí¡ßÛd´¤èô¸n4ì5ä$aoBlvÂ%¤!oÖÿCÇvbÞ=áù Q
è©=®²÷ÓåÇæ1f~xèç
fìùßÀ<!¸ÆÔ	á{nÏÃ01{E|ÅJnlÛå5o=ÝzÌs30ì@ÂØå¾ãÙ5CÌ-µ_¢ùÛ}¦+&	ÉëvVÚÁ%<oýbïÙ#caez¡¤ï:yÊÞÙBRÓÂ(ùmÏÂ³©Ïz±e[ Ðg¶Å2¤é´W)Ì`§ºðT±ÞG»uíúYoh1jã¥Bý¼yT$¼4WHkª·Gð©YúfRAjXøå8õ8XCJ{ÎG{;}ò·%´ÌôHwè1ãñÿ"uëßÝj\¼2`êå"^§ªçGéË¥¡SB¦ÇWgôW8¥SÆ´¾+5Õ[Ïå÷zgh.ðùõekKÜh}Cþà°nN=DçòÒ|ôån·?aG|ÃSÿÞ©ÄmÚH0$ëÌc5h:s59wÛC¹ü|Bþü&õÓtÓn@ç¾ÃYG9±ñ¸ùþ_ Ú>°IPZlôh0aì#óàSûÝpB9­,¿DÇL<ø|»wô=8J@R$i Þ|badc;á*¤ZXªÁSLìËí½	âòèqÓ·þ5:N¡ÆMg7ß¼ùc~µQþÄÝ/tØÑÔxõÀp*×tP¸³û¿®âÍ×pcªZy?Îøkó"Ç´Ï?E´WáPr!&pw¾Ðù1õ©ÔçåVÅHÐíÃ+¾+	¦YóEd*ÖúPÛÏJ©»Éâ ið3®Y[®*óT$ë 7Æ=xVú¢ý6ªÙöÎØ{ÔÓÛäÜVEªRÈ/'IQU¯xdé~êÑfÁ-5ð(PÄ3,;ö{Na`pìÙi.s­Ãd)               96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
202,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.496,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
202,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.512,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
202,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.528,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.544,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.56,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.576,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.592,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.608,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.624,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
499,
2
],
[
531,
5
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.64,
[
"bid",
[
[
126,
1
],
[
96,
5
],
[
78,
1
],
[
40,
3
],
[
35,
5
],
[
27,
3
],
[
2,
3
]
]
],
[
"ask",
[
[
201,
3
],
[
203,
5
],
[
347,
4
],
[
455,
1
],
[
477,
2
],
[
483,
5
],
[
499,
2
],
[
563,
2
],
[
619,
2
]
]
]
]
[
"time",
29980.656,
[
"bid",
[
[
127,
4
],
[
126,
1
],
[
96,
5
],
[
78,
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row

In [41]:
#Source code string cannot contain null bytes
#https://stackoverflow.com/questions/47336788/source-code-string-cannot-contain-null-bytes
df_2022_01_14 = Create_LOB_df_Improved(Read_LOB_Improved(
    "s3://project-b-data/proj-b/dataset-b01/Tst2022-01-14LOBs.txt"),"2022-01-14")

This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row
This is 159th 1000000 row

In [35]:
a = "[[187,1],[185,MMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMMM     2],[4,3]]"

print(ast.literal_eval(a.replace("M","").replace(" ","").replace(chr(0),"")))

[[187, 1], [185, 2], [4, 3]]

In [34]:
ast.literal_eval("[[187,1],[185,2],[4,3]]")

[[187, 1], [185, 2], [4, 3]]

In [14]:
pd.read_csv("LOB_csv/2022-01-14-LOB.csv")

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-01-14
1,1,0.016,NaN,NaN,2022-01-14
2,2,0.032,NaN,NaN,2022-01-14
3,3,0.048,NaN,NaN,2022-01-14
4,4,0.064,NaN,NaN,2022-01-14
...,...,...,...,...,...
1912487,1912487,30599.920,"[[227, 2], [225, 2], [221, 3], [188, 1], [184,...","[[230, 2], [418, 4], [428, 4], [456, 4], [534,...",2022-01-14
1912488,1912488,30599.936,"[[227, 2], [225, 2], [221, 3], [188, 1], [184,...","[[230, 2], [418, 4], [428, 4], [456, 4], [534,...",2022-01-14
1912489,1912489,30599.952,"[[227, 2], [225, 2], [221, 3], [188, 1], [184,...","[[230, 2], [418, 4], [428, 4], [456, 4], [534,...",2022-01-14
1912490,1912490,30599.968,"[[227, 2], [225, 2], [221, 3], [188, 1], [184,...","[[230, 2], [418, 4], [428, 4], [456, 4], [534,...",2022-01-14
1912491,1912491,30599.984,"[[227, 2], [225, 2], [221, 3], [188, 1], [184,...","[[230, 2], [418, 4], [428, 4], [456, 4], [534,...",2022-01-14

In [ ]:
with sm.open('Example.txt',"rb",encoding='utf-8') as f:
    example_data = f.read()
print(example_data)

In [33]:
pd.read_csv("LOB_csv/2022-01-28-LOB.csv")

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-01-28
1,1,0.016,NaN,NaN,2022-01-28
2,2,0.032,NaN,NaN,2022-01-28
3,3,0.048,NaN,NaN,2022-01-28
4,4,0.064,NaN,NaN,2022-01-28
...,...,...,...,...,...
1912487,1912487,30599.920,"[[202, 3], [199, 3], [188, 4], [173, 7], [154,...","[[213, 4], [219, 1], [220, 5], [330, 2], [377,...",2022-01-28
1912488,1912488,30599.936,"[[202, 3], [199, 3], [188, 4], [173, 7], [154,...","[[213, 4], [219, 1], [220, 5], [330, 2], [377,...",2022-01-28
1912489,1912489,30599.952,"[[202, 3], [199, 3], [188, 4], [173, 4], [154,...","[[213, 4], [219, 1], [220, 5], [330, 2], [377,...",2022-01-28
1912490,1912490,30599.968,"[[202, 3], [199, 3], [188, 4], [173, 4], [154,...","[[213, 4], [219, 1], [220, 5], [330, 2], [377,...",2022-01-28
1912491,1912491,30599.984,"[[202, 3], [199, 3], [188, 4], [173, 4], [154,...","[[213, 4], [219, 1], [220, 5], [330, 2], [377,...",2022-01-28

#### 2022-02-04

In [18]:
exact_date[31]

'2022-02-04'

In [24]:
%%time
for the_date in exact_date[31]:
    t1 = time.time()
    LOB_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/Tst'+the_date+'LOBs.txt')
    

    try:
        print(f"Start Read {the_date} LOB file.")
        Create_LOB_df_Improved(Read_LOB_Improved(
    "s3://project-b-data/proj-b/dataset-b01/Tst2022-02-04LOBs.txt"),"2022-02-04")
    except MemoryError:
        print("MemoryError!")
    except Exception as e:
        print(f"Another Error! {e}")
        
    t2 = time.time()
    print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

Start Read 2 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row
This is 23th 1000000 row
This is 24th 1000000 row
This is 25th 1000000 row
This is 26th 1000000 row
This is 27th 1000000 row
This is 28th 1000000 row
This is 29th 1000000 row
This is 30th 1000000 row
This is 31th 1000000 row
This is 32th 1000000 row
This is 33th 1000000 row
This is 34th 1000000 row
This is 35th 1000000 row
This is 36th 1000000 row
This is 37th 1000000 row
This is 38th 1000000 row
This is 39th 1000000 row
This is 40th 1000000 row
This is 41th 1000000 row
This is 42th 1000000 row
This is 43th 1000000 row
This is 44th 1000000 row
This is 45th 1000000 row
This is 46th 1000000 row
This is 47th 1000000 row
This is 48th 1000000 row
This is 49th 1000000 row
This is 50th 1000000 row
This is 51th 1000000 row
This is 52th 1000000 row
This is 53th 1000000 row
This is 54th 1000000 row
This is 55th 1000000 row
This is 56th 1000000 row
This is 57th 1000000 row
This is 58th 1000000 row
This is 59th 1000000 row
This is 60th 1000000 row
This is 61th 1000000 row
This is 62th 1000000 row
This is 63th 1000000 row
This is 64th 1000000 row
This is 65th 1000000 row
This is 66th 1000000 row
This is 67th 1000000 row
This is 68th 1000000 row
This is 69th 1000000 row
This is 70th 1000000 row
This is 71th 1000000 row
This is 72th 1000000 row
This is 73th 1000000 row
This is 74th 1000000 row
This is 75th 1000000 row
This is 76th 1000000 row
This is 77th 1000000 row
This is 78th 1000000 row
This is 79th 1000000 row
This is 80th 1000000 row
This is 81th 1000000 row
This is 82th 1000000 row
This is 83th 1000000 row
This is 84th 1000000 row
This is 85th 1000000 row
This is 86th 1000000 row
This is 87th 1000000 row
This is 88th 1000000 row
This is 89th 1000000 row
This is 90th 1000000 row
This is 91th 1000000 row
This is 92th 1000000 row
This is 93th 1000000 row
This is 94th 1000000 row
This is 95th 1000000 row
This is 96th 1000000 row
This is 97th 1000000 row
This is 98th 1000000 row
This is 99th 1000000 row
This is 100th 1000000 row
This is 101th 1000000 row
This is 102th 1000000 row
This is 103th 1000000 row
This is 104th 1000000 row
This is 105th 1000000 row
This is 106th 1000000 row
This is 107th 1000000 row
This is 108th 1000000 row
This is 109th 1000000 row
This is 110th 1000000 row
This is 111th 1000000 row
This is 112th 1000000 row
This is 113th 1000000 row
This is 114th 1000000 row
This is 115th 1000000 row
This is 116th 1000000 row
This is 117th 1000000 row
117000000
117001000
117002000
117003000
117004000
117005000
117006000
117007000
117008000
117009000
117010000
117011000
117012000
117013000
117014000
117015000
117016000
117017000
117018000
117019000
117020000
117021000
117022000
117023000
117024000
117025000
117026000
117027000
117028000
117029000
117030000
117031000
117032000
117033000
117034000
117035000
117036000
117037000
117038000
117039000
117040000
117041000
117042000
117043000
117044000
117045000
117046000
117047000
117048000
117049000
117050000
117051000
117052000
117053000
117054000
117055000
117056000
117057000
117058000
117059000
117060000
117061000
117062000
117063000
117064000
117065000
117066000
117067000
117068000
117069000
117070000
117071000
117072000
117073000
117074000
117075000
117076000
117077000
117078000
117079000
117080000
117081000
117082000
117083000
117084000
117085000
117086000
117087000
117088000
117089000
117090000
117091000
117092000
117093000
117094000
117095000
117096000
117097000
117098000
117099000
117100000
117101000
117102000
117103000
117104000
117105000
117106000
117107000
117108000
117109000
117110000
117111000
117112000
117113000
117114000
117115000
117116000
117117000
117118000
117119000
117120000
117121000
117122000
117123000
117124000
117125000
117126000
117127000
117128000
117129000
117130000
117131000
117132000
117133000
117134000
117135000
117136000
117137000
117138000
117139000
117140000
117141000
117142000
117143000
117144000
117145000
117146000
117147000
117148000
117149000
117150000
117151000
117152000
117153000
117154000
117155000
117156000
117157000
117158000
117159000
117160000
117161000
117162000
117163000
117164000
117165000
117166000
117167000
117168000
117169000
117170000
117171000
117172000
117173000
117174000
117175000
117176000
117177000
117178000
117179000
117180000
117181000
117182000
117183000
117184000
117185000
117186000
117187000
117188000
117189000
117190000
117191000
117192000
117193000
117194000
117195000
117196000
117197000
117198000
117199000
117200000
117201000
117202000
117203000
117204000
117205000
117206000
117207000
117208000
117209000
117210000
117211000
117212000
117213000
117214000
117215000
117216000
117217000
117218000
117219000
117220000
117221000
117222000
117223000
117224000
117225000
117226000
117227000
117228000
117229000
117230000
117231000
117232000
117233000
117234000
117235000
117236000
117237000
117238000
117239000
117240000
117241000
117242000
117243000
117244000
117245000
117246000
117247000
117248000
117249000
117250000
117251000
117252000
117253000
117254000
117255000
117256000
117257000
117258000
117259000
117260000
117261000
117262000
117263000
117264000
117265000
117266000
117267000
117268000
117269000
117270000
117271000
117272000
117273000
117274000
117275000
117276000
117277000
117278000
117279000
117280000
117281000
117282000
117283000
117284000
117285000
117286000
117287000
117288000
117289000
117290000
117291000
117292000
117293000
117294000
117295000
117296000
117297000
117298000
117299000
117300000
117301000
117302000
117303000
117304000
117305000
117306000
117307000
117308000
117309000
117310000
117311000
117312000
117313000
117314000
117315000
117316000
117317000
117318000
117319000
117320000
117321000
117322000
117323000
117324000
117325000
117326000
117327000
117328000
117329000
117330000
117331000
117332000
117333000
117334000
117335000
117336000
117337000
117338000
117339000
117340000
117341000
117342000
117343000
117344000
117345000
117346000
117347000
117348000
117349000
117350000
117351000
117352000
117353000
117354000
117355000
117356000
117357000
117358000
117359000
117360000
117361000
117362000
117363000
117364000
117365000
117366000
117367000
117368000
117369000
117370000
117371000
117372000
117373000
117374000
117375000
117376000
117377000
117378000
117379000
117380000
117381000
117382000
117383000
117384000
117385000
117386000
117387000
117388000
117389000
117390000
117391000
117392000
117393000
117394000
117395000
117396000
117397000
117398000
117399000
117400000
117401000
117402000
117403000
117404000
117405000
117406000
117407000
117408000
117409000
117410000
117411000
117412000
117413000
117414000
117415000
117416000
117417000
117418000
117419000
117420000
117421000
117422000
117423000
117424000
117425000
117426000
117427000
117428000
117429000
117430000
117431000
117432000
117433000
117434000
117435000
117436000
117437000
117438000
117439000
117440000
117441000
117442000
117443000
117444000
117445000
117446000
117447000
117448000
117449000
117450000
117451000
117452000
117453000
117454000
117455000
117456000
117457000
117458000
117459000
117460000
117461000
117462000
117463000
117464000
117465000
117466000
117467000
117468000
117469000
117470000
117471000
117472000
117473000
117474000
117475000
117476000
117477000
117478000
117479000
117480000
117481000
117482000
117483000
117484000
117485000
117486000
117487000
117488000
117489000
117490000
117491000
117492000
117493000
117494000
117495000
117496000
117497000
117498000
117499000
117500000
117501000
117502000
117503000
117504000
117505000
117506000
117507000
117508000
117509000
117510000
117511000
117512000
117513000
117514000
117515000
117516000
117517000
117518000
117519000
117520000
117521000
117522000
117523000
117524000
117525000
117526000
117527000
117528000
117529000
117530000
117531000
117532000
117533000
117534000
117535000
117536000
117537000
117538000
117539000
117540000
117541000
117542000
117543000
117544000
117545000
117546000
117547000
117548000
117549000
117550000
117551000
117552000
117553000
117554000
117555000
117556000
117557000
117558000
117559000
117560000
117561000
117562000
117563000
117564000
117565000
117566000
117567000
117568000
117569000
117570000
117571000
117572000
117573000
117574000
117575000
117576000
117577000
117578000
117579000
117580000
117581000
117582000
117583000
117584000
117585000
117586000
117587000
117588000
117589000
117590000
117591000
117592000
117593000
117594000
117595000
117596000
117597000
117598000
117599000
117600000
117601000
117602000
117603000
117604000
117605000
117606000
117607000
117608000
117609000
117610000
117611000
117612000
117613000
117614000
117615000
117616000
117617000
117618000
117619000
117620000
117621000
117622000
117623000
117624000
117625000
117626000
117627000
117628000
117629000
117630000
117631000
117632000
117633000
117634000
117635000
117636000
117637000
117638000
117639000
117640000
117641000
117642000
117643000
117644000
117645000
117646000
117647000
117648000
117649000
117650000
117651000
117652000
117653000
117654000
117655000
117656000
117657000
117658000
117659000
117660000
117661000
117662000
117663000
117664000
117665000
117666000
117667000
117668000
117669000
117670000
117671000
117672000
117673000
117674000
117675000
117676000
117677000
117678000
117679000
117680000
117681000
117682000
117683000
117684000
117685000
117686000
117687000
117688000
117689000
117690000
117691000
117692000
117693000
117694000
117695000
117696000
117697000
117698000
117699000
117700000
117701000
117702000
117703000
117704000
117705000
117706000
117707000
117708000
117709000
117710000
117711000
117712000
117713000
117714000
117715000
117716000
117717000
117718000
117719000
117720000
117721000
117722000
117723000
117724000
117725000
117726000
117727000
117728000
117729000
117730000
117731000
117732000
117733000
117734000
117735000
117736000
117737000
117738000
117739000
117740000
117741000
117742000
117743000
117744000
117745000
117746000
117747000
117748000
117749000
117750000
117751000
117752000
117753000
117754000
117755000
117756000
117757000
117758000
117759000
117760000
117761000
117762000
117763000
117764000
117765000
117766000
117767000
117768000
117769000
117770000
117771000
117772000
117773000
117774000
117775000
117776000
117777000
117778000
117779000
117780000
117781000
117782000
117783000
117784000
117785000
117786000
117787000
117788000
117789000
117790000
117791000
117792000
117793000
117794000
117795000
117796000
117797000
117798000
117799000
117800000
117801000
117802000
117803000
117804000
117805000
117806000
117807000
117808000
117809000
117810000
117811000
117812000
117813000
117814000
117815000
117816000
117817000
117818000
117819000
117820000
117821000
117822000
117823000
117824000
117825000
117826000
117827000
117828000
117829000
117830000
117831000
117832000
117833000
117834000
117835000
117836000
117837000
117838000
117839000
117840000
117841000
117842000
117843000
117844000
117845000
117846000
117847000
117848000
117849000
117850000
117851000
117852000
117853000
117854000
117855000
117856000
117857000
117858000
117859000
117860000
117861000
117862000
117863000
117864000
117865000
117866000
117867000
117868000
117869000
117870000
117871000
117872000
117873000
117874000
117875000
117876000
117877000
117878000
117879000
117880000
117881000
117882000
117883000
117884000
117885000
117886000
117887000
117888000
117889000
117890000
117891000
117892000
117893000
117894000
117895000
117896000
117897000
117898000
117899000
117900000
117901000
117902000
117903000
117904000
117905000
117906000
117907000
117908000
117909000
117910000
117911000
117912000
117913000
117914000
117915000
117916000
117917000
117918000
117919000
117920000
117921000
117922000
117923000
117924000
117925000
117926000
117927000
117928000
117929000
117930000
117931000
117932000
117933000
117934000
117935000
117936000
117937000
117938000
117939000
117940000
117941000
117942000
117943000
117944000
117945000
117946000
117947000
117948000
117949000
117950000
117951000
117952000
117953000
117954000
117955000
117956000
117957000
117958000
117959000
117960000
117961000
117962000
117963000
117964000
117965000
117966000
117967000
117968000
117969000
117970000
117971000
117972000
117973000
117974000
117975000
117976000
117977000
117978000
117979000
117980000
117981000
117982000
117983000
117984000
117985000
117986000
117987000
117988000
117989000
117990000
117991000
117992000
117993000
117994000
117995000
117996000
117997000
117998000
117999000
This is 118th 1000000 row
This is 119th 1000000 row
This is 120th 1000000 row
This is 121th 1000000 row
This is 122th 1000000 row
This is 123th 1000000 row
This is 124th 1000000 row
This is 125th 1000000 row
This is 126th 1000000 row
This is 127th 1000000 row
This is 128th 1000000 row
This is 129th 1000000 row
This is 130th 1000000 row
This is 131th 1000000 row
This is 132th 1000000 row
This is 133th 1000000 row
This is 134th 1000000 row
This is 135th 1000000 row
This is 136th 1000000 row
This is 137th 1000000 row
This is 138th 1000000 row
This is 139th 1000000 row
This is 140th 1000000 row
This is 141th 1000000 row
This is 142th 1000000 row
This is 143th 1000000 row
This is 144th 1000000 row
This is 145th 1000000 row
This is 146th 1000000 row
This is 147th 1000000 row
This is 148th 1000000 row
This is 149th 1000000 row
This is 150th 1000000 row
This is 151th 1000000 row
This is 152th 1000000 row
This is 153th 1000000 row
This is 154th 1000000 row
This is 155th 1000000 row
This is 156th 1000000 row
This is 157th 1000000 row
This is 158th 1000000 row
The 2 is finished. Elapsed time is 527.1843135356903 seconds.
Start Read 0 LOB file.
This is 0th 1000000 row
This is 1th 1000000 row
This is 2th 1000000 row
This is 3th 1000000 row
This is 4th 1000000 row
This is 5th 1000000 row
This is 6th 1000000 row
This is 7th 1000000 row
This is 8th 1000000 row
This is 9th 1000000 row
This is 10th 1000000 row
This is 11th 1000000 row
This is 12th 1000000 row
This is 13th 1000000 row
This is 14th 1000000 row
This is 15th 1000000 row
This is 16th 1000000 row
This is 17th 1000000 row
This is 18th 1000000 row
This is 19th 1000000 row
This is 20th 1000000 row
This is 21th 1000000 row
This is 22th 1000000 row

KeyboardInterrupt:

In [25]:
pd.read_csv("LOB_csv/2022-02-04-LOB.csv")

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-02-04
1,1,0.016,NaN,NaN,2022-02-04
2,2,0.032,NaN,NaN,2022-02-04
3,3,0.048,NaN,NaN,2022-02-04
4,4,0.064,NaN,NaN,2022-02-04
...,...,...,...,...,...
1912491,1912491,30599.920,"[[185, 3], [184, 2], [133, 1], [97, 2], [84, 3...","[[190, 4], [276, 1], [342, 2], [476, 2], [479,...",2022-02-04
1912492,1912492,30599.936,"[[185, 3], [184, 2], [133, 1], [97, 2], [84, 3...","[[190, 1], [276, 1], [342, 2], [476, 2], [479,...",2022-02-04
1912493,1912493,30599.952,"[[185, 3], [184, 2], [133, 1], [97, 2], [84, 3...","[[190, 1], [276, 1], [342, 2], [476, 2], [479,...",2022-02-04
1912494,1912494,30599.968,"[[185, 3], [184, 2], [133, 1], [97, 2], [84, 3...","[[190, 1], [276, 1], [342, 2], [476, 2], [479,...",2022-02-04
1912495,1912495,30599.984,"[[185, 3], [184, 2], [133, 1], [97, 2], [84, 3...","[[190, 1], [276, 1], [342, 2], [476, 2], [479,...",2022-02-04

In [31]:
pd.read_csv("LOB_csv/2022-03-03-LOB.csv")

,Unnamed: 0,Time,Bid,Ask,Date
0,0,0.000,NaN,NaN,2022-03-03
1,1,0.016,NaN,NaN,2022-03-03
2,2,0.032,NaN,NaN,2022-03-03
3,3,0.048,NaN,NaN,2022-03-03
4,4,0.064,NaN,NaN,2022-03-03
...,...,...,...,...,...
1912495,1912495,30599.920,"[[197, 5], [183, 2], [181, 1], [166, 3], [154,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912496,1912496,30599.936,"[[197, 5], [183, 2], [181, 1], [166, 3], [154,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912497,1912497,30599.952,"[[197, 5], [183, 2], [181, 1], [154, 4], [138,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912498,1912498,30599.968,"[[197, 5], [183, 2], [181, 1], [154, 4], [138,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03
1912499,1912499,30599.984,"[[197, 5], [183, 2], [181, 1], [154, 4], [138,...","[[274, 5], [275, 4], [387, 2], [410, 5], [488,...",2022-03-03