In [1]:
from sagemaker import get_execution_role
role = get_execution_role()

#Bucket and Folder
bucket = 'project-b-new'
subfolder = 'dataset-b03'

In [2]:
import boto3
conn = boto3.client('s3')
contents = conn.list_objects(Bucket=bucket, Prefix=subfolder)['Contents']
#Data Set Name
for i in range(5):
    print(contents[i]['Key'])

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

dataset-b03/AAA_READ_ME_DS03.txt
dataset-b03/TstB03_2022-01-04LOBs.txt
dataset-b03/TstB03_2022-01-04tapes.csv
dataset-b03/TstB03_2022-01-05LOBs.txt
dataset-b03/TstB03_2022-01-05tapes.csv

In [3]:
#Generate String Date
import pandas as pd
import time
import re
date_list = pd.date_range(start = "2022-01-04",end = "2022-04-29").tolist()
exact_date = [str(i)[0:10] for i in date_list]   #2022-01-04 format"
print(exact_date[:5])

['2022-01-04', '2022-01-05', '2022-01-06', '2022-01-07', '2022-01-08']

In [4]:
tape_csv = []

total_time = 0
for the_date in exact_date:
    t1 = time.time()
    tape_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/TstB03_'+the_date+'tapes.csv')

    try: 
        tape_csv.append(pd.DataFrame(pd.read_csv(tape_from_s3,header = None)))
    except:
        continue
    t2 = time.time()
    total_time += t2 - t1
    print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

print("Total .csv file Read time: {}".format(total_time))

The 2022-01-04 is finished. Elapsed time is 0.9747812747955322 seconds.
The 2022-01-05 is finished. Elapsed time is 0.5013697147369385 seconds.
The 2022-01-06 is finished. Elapsed time is 0.4345052242279053 seconds.
The 2022-01-07 is finished. Elapsed time is 0.46585845947265625 seconds.
The 2022-01-10 is finished. Elapsed time is 0.5970578193664551 seconds.
The 2022-01-11 is finished. Elapsed time is 0.36262965202331543 seconds.
The 2022-01-12 is finished. Elapsed time is 0.38181614875793457 seconds.
The 2022-01-13 is finished. Elapsed time is 0.3251817226409912 seconds.
The 2022-01-14 is finished. Elapsed time is 0.3408780097961426 seconds.
The 2022-01-17 is finished. Elapsed time is 0.2864079475402832 seconds.
The 2022-01-18 is finished. Elapsed time is 0.35210132598876953 seconds.
The 2022-01-19 is finished. Elapsed time is 0.35260891914367676 seconds.
The 2022-01-20 is finished. Elapsed time is 0.382218599319458 seconds.
The 2022-01-21 is finished. Elapsed time is 0.320070743560791 seconds.
The 2022-01-24 is finished. Elapsed time is 0.24579167366027832 seconds.
The 2022-01-25 is finished. Elapsed time is 0.46626830101013184 seconds.
The 2022-01-26 is finished. Elapsed time is 0.2659027576446533 seconds.
The 2022-01-27 is finished. Elapsed time is 0.32620811462402344 seconds.
The 2022-01-28 is finished. Elapsed time is 0.26121020317077637 seconds.
The 2022-01-31 is finished. Elapsed time is 0.2989158630371094 seconds.
The 2022-02-01 is finished. Elapsed time is 0.3020308017730713 seconds.
The 2022-02-02 is finished. Elapsed time is 0.2979001998901367 seconds.
The 2022-02-03 is finished. Elapsed time is 0.2728853225708008 seconds.
The 2022-02-04 is finished. Elapsed time is 0.420090913772583 seconds.
The 2022-02-07 is finished. Elapsed time is 0.28934311866760254 seconds.
The 2022-02-08 is finished. Elapsed time is 0.2869300842285156 seconds.
The 2022-02-09 is finished. Elapsed time is 0.21143603324890137 seconds.
The 2022-02-10 is finished. Elapsed time is 0.4554591178894043 seconds.
The 2022-02-11 is finished. Elapsed time is 0.3217761516571045 seconds.
The 2022-02-14 is finished. Elapsed time is 0.34853243827819824 seconds.
The 2022-02-15 is finished. Elapsed time is 0.45181894302368164 seconds.
The 2022-02-16 is finished. Elapsed time is 0.31527137756347656 seconds.
The 2022-02-17 is finished. Elapsed time is 0.36391282081604004 seconds.
The 2022-02-18 is finished. Elapsed time is 0.4186525344848633 seconds.
The 2022-02-21 is finished. Elapsed time is 0.40803956985473633 seconds.
The 2022-02-22 is finished. Elapsed time is 0.40879058837890625 seconds.
The 2022-02-23 is finished. Elapsed time is 0.46767520904541016 seconds.
The 2022-02-24 is finished. Elapsed time is 0.49448323249816895 seconds.
The 2022-02-25 is finished. Elapsed time is 0.5074493885040283 seconds.
The 2022-02-28 is finished. Elapsed time is 0.441845178604126 seconds.
The 2022-03-01 is finished. Elapsed time is 0.6015217304229736 seconds.
The 2022-03-02 is finished. Elapsed time is 0.48907899856567383 seconds.
The 2022-03-03 is finished. Elapsed time is 0.38556480407714844 seconds.
The 2022-03-04 is finished. Elapsed time is 0.5762283802032471 seconds.
The 2022-03-07 is finished. Elapsed time is 0.27157044410705566 seconds.
The 2022-03-08 is finished. Elapsed time is 0.3157224655151367 seconds.
The 2022-03-09 is finished. Elapsed time is 0.31727123260498047 seconds.
The 2022-03-10 is finished. Elapsed time is 0.5505280494689941 seconds.
The 2022-03-11 is finished. Elapsed time is 0.40595340728759766 seconds.
The 2022-03-14 is finished. Elapsed time is 0.30583834648132324 seconds.
The 2022-03-15 is finished. Elapsed time is 0.45717930793762207 seconds.
The 2022-03-16 is finished. Elapsed time is 0.4317173957824707 seconds.
The 2022-03-17 is finished. Elapsed time is 0.39231157302856445 seconds.
The 2022-03-18 is finished. Elapsed time is 0.4949681758880615 seconds.
The 2022-03-21 is finished. Elapsed time is 0.43312931060791016 seconds.
The 2022-03-22 is finished. Elapsed time is 0.603430986404419 seconds.
The 2022-03-23 is finished. Elapsed time is 0.7068815231323242 seconds.
The 2022-03-24 is finished. Elapsed time is 0.35602545738220215 seconds.
The 2022-03-25 is finished. Elapsed time is 0.3842191696166992 seconds.
The 2022-03-28 is finished. Elapsed time is 0.48671698570251465 seconds.
The 2022-03-29 is finished. Elapsed time is 0.5215072631835938 seconds.
The 2022-03-30 is finished. Elapsed time is 0.47162318229675293 seconds.
The 2022-03-31 is finished. Elapsed time is 0.41042494773864746 seconds.
The 2022-04-01 is finished. Elapsed time is 0.4918386936187744 seconds.
The 2022-04-04 is finished. Elapsed time is 0.5705125331878662 seconds.
The 2022-04-05 is finished. Elapsed time is 0.6009187698364258 seconds.
The 2022-04-06 is finished. Elapsed time is 0.5385031700134277 seconds.
The 2022-04-07 is finished. Elapsed time is 0.4375951290130615 seconds.
The 2022-04-08 is finished. Elapsed time is 0.3560645580291748 seconds.
The 2022-04-11 is finished. Elapsed time is 0.3815436363220215 seconds.
The 2022-04-12 is finished. Elapsed time is 0.4091935157775879 seconds.
The 2022-04-13 is finished. Elapsed time is 0.48287510871887207 seconds.
The 2022-04-14 is finished. Elapsed time is 0.47884607315063477 seconds.
The 2022-04-19 is finished. Elapsed time is 0.451063871383667 seconds.
The 2022-04-20 is finished. Elapsed time is 0.5826151371002197 seconds.
The 2022-04-21 is finished. Elapsed time is 0.5138804912567139 seconds.
The 2022-04-22 is finished. Elapsed time is 0.33971309661865234 seconds.
The 2022-04-25 is finished. Elapsed time is 0.3334507942199707 seconds.
The 2022-04-26 is finished. Elapsed time is 0.4371323585510254 seconds.
The 2022-04-27 is finished. Elapsed time is 0.26438212394714355 seconds.
The 2022-04-28 is finished. Elapsed time is 0.41537046432495117 seconds.
The 2022-04-29 is finished. Elapsed time is 0.5073602199554443 seconds.
Total .csv file Read time: 34.388378381729126

In [5]:
#Concatenate all the csv file into one data frame 



full_csv_frame = pd.concat(tape_csv)
print("There are {} rows and {} columns of the full csv frame.".format(full_csv_frame.shape[0],full_csv_frame.shape[1]))
print(full_csv_frame[:5])
full_csv_frame.to_csv("Tape_csv/Full_tapeB03.csv",index = False)

There are 3067130 rows and 11 columns of the full csv frame.
                  0          1      2    3                        4   \
0  TstB03_2022-01-04   Exch0Lit  7.089  263   {'pool_id': 'Exch0Lit'
1  TstB03_2022-01-04   Exch0Lit  7.089  263   {'pool_id': 'Exch0Lit'
2  TstB03_2022-01-04   Exch0Lit  8.619  259   {'pool_id': 'Exch0Lit'
3  TstB03_2022-01-04   Exch0Lit  8.908  259   {'pool_id': 'Exch0Lit'
4  TstB03_2022-01-04   Exch0Lit  9.588  260   {'pool_id': 'Exch0Lit'

                 5               6              7          8   \
0   'type': 'Trade'   'time': 7.089   'price': 263   'qty': 3
1   'type': 'Trade'   'time': 7.089   'price': 263   'qty': 2
2   'type': 'Trade'   'time': 8.619   'price': 259   'qty': 1
3   'type': 'Trade'   'time': 8.908   'price': 259   'qty': 2
4   'type': 'Trade'   'time': 9.588   'price': 260   'qty': 2

                 9                  10
0   'party1': 'S19'   'party2': 'B15'}
1   'party1': 'S13'   'party2': 'B15'}
2   'party1': 'S10'   'party2': 'B02'}
3   'party1': 'S10'   'party2': 'B18'}
4   'party1': 'S17'   'party2': 'B11'}

In [7]:
full_csv_frame

,0,1,2,3,4,5,6,7,8,9,10
0,TstB03_2022-01-04,Exch0Lit,7.089,263,{'pool_id': 'Exch0Lit','type': 'Trade','time': 7.089,'price': 263,'qty': 3,'party1': 'S19','party2': 'B15'}
1,TstB03_2022-01-04,Exch0Lit,7.089,263,{'pool_id': 'Exch0Lit','type': 'Trade','time': 7.089,'price': 263,'qty': 2,'party1': 'S13','party2': 'B15'}
2,TstB03_2022-01-04,Exch0Lit,8.619,259,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.619,'price': 259,'qty': 1,'party1': 'S10','party2': 'B02'}
3,TstB03_2022-01-04,Exch0Lit,8.908,259,{'pool_id': 'Exch0Lit','type': 'Trade','time': 8.908,'price': 259,'qty': 2,'party1': 'S10','party2': 'B18'}
4,TstB03_2022-01-04,Exch0Lit,9.588,260,{'pool_id': 'Exch0Lit','type': 'Trade','time': 9.588,'price': 260,'qty': 2,'party1': 'S17','party2': 'B11'}
...,...,...,...,...,...,...,...,...,...,...,...
36622,TstB03_2022-04-29,Exch0Lit,30595.597,227,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30595.597,'price': 227,'qty': 2,'party1': 'S03','party2': 'B29'}
36623,TstB03_2022-04-29,Exch0Lit,30598.657,224,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30598.657,'price': 224,'qty': 1,'party1': 'S15','party2': 'B27'}
36624,TstB03_2022-04-29,Exch0Lit,30598.691,224,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30598.691,'price': 224,'qty': 1,'party1': 'S15','party2': 'B16'}
36625,TstB03_2022-04-29,Exch0Lit,30598.810,224,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30598.81,'price': 224,'qty': 2,'party1': 'S23','party2': 'B05'}
36626,TstB03_2022-04-29,Exch0Lit,30599.983,225,{'pool_id': 'Exch0Lit','type': 'Trade','time': 30599.983,'price': 225,'qty': 4,'party1': 'S21','party2': 'B07'}

In [6]:
for column in full_csv_frame:
    print(full_csv_frame[column].unique())

['TstB03_2022-01-04' 'TstB03_2022-01-05' 'TstB03_2022-01-06'
 'TstB03_2022-01-07' 'TstB03_2022-01-10' 'TstB03_2022-01-11'
 'TstB03_2022-01-12' 'TstB03_2022-01-13' 'TstB03_2022-01-14'
 'TstB03_2022-01-17' 'TstB03_2022-01-18' 'TstB03_2022-01-19'
 'TstB03_2022-01-20' 'TstB03_2022-01-21' 'TstB03_2022-01-24'
 'TstB03_2022-01-25' 'TstB03_2022-01-26' 'TstB03_2022-01-27'
 'TstB03_2022-01-28' 'TstB03_2022-01-31' 'TstB03_2022-02-01'
 'TstB03_2022-02-02' 'TstB03_2022-02-03' 'TstB03_2022-02-04'
 'TstB03_2022-02-07' 'TstB03_2022-02-08' 'TstB03_2022-02-09'
 'TstB03_2022-02-10' 'TstB03_2022-02-11' 'TstB03_2022-02-14'
 'TstB03_2022-02-15' 'TstB03_2022-02-16' 'TstB03_2022-02-17'
 'TstB03_2022-02-18' 'TstB03_2022-02-21' 'TstB03_2022-02-22'
 'TstB03_2022-02-23' 'TstB03_2022-02-24' 'TstB03_2022-02-25'
 'TstB03_2022-02-28' 'TstB03_2022-03-01' 'TstB03_2022-03-02'
 'TstB03_2022-03-03' 'TstB03_2022-03-04' 'TstB03_2022-03-07'
 'TstB03_2022-03-08' 'TstB03_2022-03-09' 'TstB03_2022-03-10'
 'TstB03_2022-03-11' 'TstB03_2022-03-14' 'TstB03_2022-03-15'
 'TstB03_2022-03-16' 'TstB03_2022-03-17' 'TstB03_2022-03-18'
 'TstB03_2022-03-21' 'TstB03_2022-03-22' 'TstB03_2022-03-23'
 'TstB03_2022-03-24' 'TstB03_2022-03-25' 'TstB03_2022-03-28'
 'TstB03_2022-03-29' 'TstB03_2022-03-30' 'TstB03_2022-03-31'
 'TstB03_2022-04-01' 'TstB03_2022-04-04' 'TstB03_2022-04-05'
 'TstB03_2022-04-06' 'TstB03_2022-04-07' 'TstB03_2022-04-08'
 'TstB03_2022-04-11' 'TstB03_2022-04-12' 'TstB03_2022-04-13'
 'TstB03_2022-04-14' 'TstB03_2022-04-19' 'TstB03_2022-04-20'
 'TstB03_2022-04-21' 'TstB03_2022-04-22' 'TstB03_2022-04-25'
 'TstB03_2022-04-26' 'TstB03_2022-04-27' 'TstB03_2022-04-28'
 'TstB03_2022-04-29']
[' Exch0Lit']
[7.0890000e+00 8.6190000e+00 8.9080000e+00 ... 3.0567836e+04 3.0578903e+04
 3.0585431e+04]
[263 259 260 258 254 256 257 265 264 266 267 262 268 261 253 255 252 251
 250 249 246 248 247 245 244 243 242 241 240 239 238 237 236 235 234 233
 232 231 230 229 228 227 225 226 224 223 222 221 220 218 219 217 215 216
 214 213 212 211 209 210 207 208 206 205 204 203 270 269 272 271 273 274
 276 275 277 278 279 202 201 200 199 280 281 282 283 284 287 288 286 285
 289 290 291 292 293 294 295 296 297 298 299 300 301 302 303 305 304 306
 307 309 308 311 310 312 314 313 315 316 317 318 319 320 321 323 322 324
 325 326 327 329 328 331 330 332 333 335 334 336 338 337 339 340 341 343
 342 344 347 345 346 348 349 350 354 352 351 353 355 356 358 357 359 361
 360 362 363 364 365 366 367 369 368 370 371 374 373 372 376 378 375 377
 382 381 379 380 198 197 196 195 194 193 192 191 190 189 188 187 186 185
 184 183 182 180 181 179 178 177 176 175 174 173 172 171 170 168 169 167
 166 165 164 163 162 161 160 159 158 157 156 155 154 153 152 151 150 149]
[" {'pool_id': 'Exch0Lit'"]
[" 'type': 'Trade'"]
[" 'time': 7.089" " 'time': 8.619" " 'time': 8.908" ...
 " 'time': 30567.836" " 'time': 30578.903" " 'time': 30585.431"]
[" 'price': 263" " 'price': 259" " 'price': 260" " 'price': 258"
 " 'price': 254" " 'price': 256" " 'price': 257" " 'price': 265"
 " 'price': 264" " 'price': 266" " 'price': 267" " 'price': 262"
 " 'price': 268" " 'price': 261" " 'price': 253" " 'price': 255"
 " 'price': 252" " 'price': 251" " 'price': 250" " 'price': 249"
 " 'price': 246" " 'price': 248" " 'price': 247" " 'price': 245"
 " 'price': 244" " 'price': 243" " 'price': 242" " 'price': 241"
 " 'price': 240" " 'price': 239" " 'price': 238" " 'price': 237"
 " 'price': 236" " 'price': 235" " 'price': 234" " 'price': 233"
 " 'price': 232" " 'price': 231" " 'price': 230" " 'price': 229"
 " 'price': 228" " 'price': 227" " 'price': 225" " 'price': 226"
 " 'price': 224" " 'price': 223" " 'price': 222" " 'price': 221"
 " 'price': 220" " 'price': 218" " 'price': 219" " 'price': 217"
 " 'price': 215" " 'price': 216" " 'price': 214" " 'price': 213"
 " 'price': 212" " 'price': 211" " 'price': 209" " 'price': 210"
 " 'price': 207" " 'price': 208" " 'price': 206" " 'price': 205"
 " 'price': 204" " 'price': 203" " 'price': 270" " 'price': 269"
 " 'price': 272" " 'price': 271" " 'price': 273" " 'price': 274"
 " 'price': 276" " 'price': 275" " 'price': 277" " 'price': 278"
 " 'price': 279" " 'price': 202" " 'price': 201" " 'price': 200"
 " 'price': 199" " 'price': 280" " 'price': 281" " 'price': 282"
 " 'price': 283" " 'price': 284" " 'price': 287" " 'price': 288"
 " 'price': 286" " 'price': 285" " 'price': 289" " 'price': 290"
 " 'price': 291" " 'price': 292" " 'price': 293" " 'price': 294"
 " 'price': 295" " 'price': 296" " 'price': 297" " 'price': 298"
 " 'price': 299" " 'price': 300" " 'price': 301" " 'price': 302"
 " 'price': 303" " 'price': 305" " 'price': 304" " 'price': 306"
 " 'price': 307" " 'price': 309" " 'price': 308" " 'price': 311"
 " 'price': 310" " 'price': 312" " 'price': 314" " 'price': 313"
 " 'price': 315" " 'price': 316" " 'price': 317" " 'price': 318"
 " 'price': 319" " 'price': 320" " 'price': 321" " 'price': 323"
 " 'price': 322" " 'price': 324" " 'price': 325" " 'price': 326"
 " 'price': 327" " 'price': 329" " 'price': 328" " 'price': 331"
 " 'price': 330" " 'price': 332" " 'price': 333" " 'price': 335"
 " 'price': 334" " 'price': 336" " 'price': 338" " 'price': 337"
 " 'price': 339" " 'price': 340" " 'price': 341" " 'price': 343"
 " 'price': 342" " 'price': 344" " 'price': 347" " 'price': 345"
 " 'price': 346" " 'price': 348" " 'price': 349" " 'price': 350"
 " 'price': 354" " 'price': 352" " 'price': 351" " 'price': 353"
 " 'price': 355" " 'price': 356" " 'price': 358" " 'price': 357"
 " 'price': 359" " 'price': 361" " 'price': 360" " 'price': 362"
 " 'price': 363" " 'price': 364" " 'price': 365" " 'price': 366"
 " 'price': 367" " 'price': 369" " 'price': 368" " 'price': 370"
 " 'price': 371" " 'price': 374" " 'price': 373" " 'price': 372"
 " 'price': 376" " 'price': 378" " 'price': 375" " 'price': 377"
 " 'price': 382" " 'price': 381" " 'price': 379" " 'price': 380"
 " 'price': 198" " 'price': 197" " 'price': 196" " 'price': 195"
 " 'price': 194" " 'price': 193" " 'price': 192" " 'price': 191"
 " 'price': 190" " 'price': 189" " 'price': 188" " 'price': 187"
 " 'price': 186" " 'price': 185" " 'price': 184" " 'price': 183"
 " 'price': 182" " 'price': 180" " 'price': 181" " 'price': 179"
 " 'price': 178" " 'price': 177" " 'price': 176" " 'price': 175"
 " 'price': 174" " 'price': 173" " 'price': 172" " 'price': 171"
 " 'price': 170" " 'price': 168" " 'price': 169" " 'price': 167"
 " 'price': 166" " 'price': 165" " 'price': 164" " 'price': 163"
 " 'price': 162" " 'price': 161" " 'price': 160" " 'price': 159"
 " 'price': 158" " 'price': 157" " 'price': 156" " 'price': 155"
 " 'price': 154" " 'price': 153" " 'price': 152" " 'price': 151"
 " 'price': 150" " 'price': 149"]
[" 'qty': 3" " 'qty': 2" " 'qty': 1" " 'qty': 4" " 'qty': 5"]
[" 'party1': 'S19'" " 'party1': 'S13'" " 'party1': 'S10'"
 " 'party1': 'S17'" " 'party1': 'S18'" " 'party1': 'S23'"
 " 'party1': 'S26'" " 'party1': 'S05'" " 'party1': 'S24'"
 " 'party1': 'S01'" " 'party1': 'S02'" " 'party1': 'S12'"
 " 'party1': 'S03'" " 'party1': 'S21'" " 'party1': 'S22'"
 " 'party1': 'S14'" " 'party1': 'S00'" " 'party1': 'S04'"
 " 'party1': 'S08'" " 'party1': 'S06'" " 'party1': 'S11'"
 " 'party1': 'S27'" " 'party1': 'S16'" " 'party1': 'S07'"
 " 'party1': 'S09'" " 'party1': 'S20'" " 'party1': 'S15'"
 " 'party1': 'S29'" " 'party1': 'S25'" " 'party1': 'S28'"]
[" 'party2': 'B15'}" " 'party2': 'B02'}" " 'party2': 'B18'}"
 " 'party2': 'B11'}" " 'party2': 'B05'}" " 'party2': 'B22'}"
 " 'party2': 'B07'}" " 'party2': 'B04'}" " 'party2': 'B19'}"
 " 'party2': 'B06'}" " 'party2': 'B08'}" " 'party2': 'B10'}"
 " 'party2': 'B29'}" " 'party2': 'B01'}" " 'party2': 'B27'}"
 " 'party2': 'B25'}" " 'party2': 'B28'}" " 'party2': 'B03'}"
 " 'party2': 'B23'}" " 'party2': 'B12'}" " 'party2': 'B13'}"
 " 'party2': 'B09'}" " 'party2': 'B14'}" " 'party2': 'B00'}"
 " 'party2': 'B26'}" " 'party2': 'B17'}" " 'party2': 'B24'}"
 " 'party2': 'B20'}" " 'party2': 'B16'}" " 'party2': 'B21'}"]

In [8]:
tape = pd.read_csv("Tape_csv/Full_tapeB03.csv")

In [9]:
new_tape = tape.rename(columns = {"0":"Date",
                       "2":"Time","3":"Price","8":"Quantity",
                      "9":"Party1","10":"Party2"}).drop(['1',"4","5","6","7"],axis = 1)
new_tape

,Date,Time,Price,Quantity,Party1,Party2
0,TstB03_2022-01-04,7.089,263,'qty': 3,'party1': 'S19','party2': 'B15'}
1,TstB03_2022-01-04,7.089,263,'qty': 2,'party1': 'S13','party2': 'B15'}
2,TstB03_2022-01-04,8.619,259,'qty': 1,'party1': 'S10','party2': 'B02'}
3,TstB03_2022-01-04,8.908,259,'qty': 2,'party1': 'S10','party2': 'B18'}
4,TstB03_2022-01-04,9.588,260,'qty': 2,'party1': 'S17','party2': 'B11'}
...,...,...,...,...,...,...
3067125,TstB03_2022-04-29,30595.597,227,'qty': 2,'party1': 'S03','party2': 'B29'}
3067126,TstB03_2022-04-29,30598.657,224,'qty': 1,'party1': 'S15','party2': 'B27'}
3067127,TstB03_2022-04-29,30598.691,224,'qty': 1,'party1': 'S15','party2': 'B16'}
3067128,TstB03_2022-04-29,30598.810,224,'qty': 2,'party1': 'S23','party2': 'B05'}
3067129,TstB03_2022-04-29,30599.983,225,'qty': 4,'party1': 'S21','party2': 'B07'}

In [10]:
new_tape["Date"] = list(map(lambda x:x[7:],new_tape["Date"]))
new_tape["Quantity"] = list(map(lambda x: float(x[-1]),new_tape["Quantity"]))
new_tape["Party1"] = list(map(lambda x: re.findall(r"S[\d][\d]",x)[0],new_tape["Party1"]))
new_tape["Party2"] = list(map(lambda x: re.findall(r"B[\d][\d]",x)[0],new_tape["Party2"]))
new_tape

               Date       Time  Price  Quantity Party1 Party2
0        2022-01-04      7.089    263       3.0    S19    B15
1        2022-01-04      7.089    263       2.0    S13    B15
2        2022-01-04      8.619    259       1.0    S10    B02
3        2022-01-04      8.908    259       2.0    S10    B18
4        2022-01-04      9.588    260       2.0    S17    B11
...             ...        ...    ...       ...    ...    ...
3067125  2022-04-29  30595.597    227       2.0    S03    B29
3067126  2022-04-29  30598.657    224       1.0    S15    B27
3067127  2022-04-29  30598.691    224       1.0    S15    B16
3067128  2022-04-29  30598.810    224       2.0    S23    B05
3067129  2022-04-29  30599.983    225       4.0    S21    B07

[3067130 rows x 6 columns]

In [11]:
new_tape["Time"]  = new_tape["Time"].round(decimals = 3)

In [12]:
new_tape.dtypes

Date         object
Time        float64
Price         int64
Quantity    float64
Party1       object
Party2       object
dtype: object

In [13]:
new_tape.to_csv("Tape_csv/Full_tape_B03.csv",index = False)

In [14]:
pd.read_csv("Tape_csv/Full_tape_B03.csv")

               Date       Time  Price  Quantity Party1 Party2
0        2022-01-04      7.089    263       3.0    S19    B15
1        2022-01-04      7.089    263       2.0    S13    B15
2        2022-01-04      8.619    259       1.0    S10    B02
3        2022-01-04      8.908    259       2.0    S10    B18
4        2022-01-04      9.588    260       2.0    S17    B11
...             ...        ...    ...       ...    ...    ...
3067125  2022-04-29  30595.597    227       2.0    S03    B29
3067126  2022-04-29  30598.657    224       1.0    S15    B27
3067127  2022-04-29  30598.691    224       1.0    S15    B16
3067128  2022-04-29  30598.810    224       2.0    S23    B05
3067129  2022-04-29  30599.983    225       4.0    S21    B07

[3067130 rows x 6 columns]

In [15]:
%%time
new_tape.to_csv(f"s3://project-b-new/Tape_csv/New_Full_Tape_B03.csv",index = False)

CPU times: user 9.83 s, sys: 179 ms, total: 10 s
Wall time: 12.9 s

## LOB

In [4]:
!pip install smart_open

import re
import smart_open as sm
import ast

Collecting smart_open
  Downloading smart_open-6.0.0-py3-none-any.whl (58 kB)
     |████████████████████████████████| 58 kB 10.2 MB/s
Installing collected packages: smart-open
Successfully installed smart-open-6.0.0

In [18]:
%%time
print(sum(1 for line in sm.open('s3://project-b-new/dataset-b03/TstB03_2022-01-04LOBs.txt',"r",encoding='utf-8')))

1800000
CPU times: user 1.78 s, sys: 420 ms, total: 2.2 s
Wall time: 16.8 s

In [19]:
a = ["time", 1.428, ["bid", [[92, 5], [91, 2], [1, 3]]], ["ask", [[310, 5], [798, 4], [799, 1]]]]
print(a)
print(a[1])
print(a[2][1])
print(a[3][1])

['time', 1.428, ['bid', [[92, 5], [91, 2], [1, 3]]], ['ask', [[310, 5], [798, 4], [799, 1]]]]
1.428
[[92, 5], [91, 2], [1, 3]]
[[310, 5], [798, 4], [799, 1]]

In [5]:
def Read_LOB_Improved(source):
    LOB_subset_time = []
    LOB_subset_bid = []
    LOB_subset_ask = []

    #Attention: errors = "ignore" for 2022-01-28
    with sm.open(source,"r",encoding="utf-8",errors = "ignore") as f:
        for i,line in enumerate(f):
            if i% 18000 == 0:
                print(f"This is {i//18000}th 18000 row")
            try: 
                result_list = ast.literal_eval(line)
            except:
                raise Exception(f"Something Wrong in {i} line!")
                
            LOB_subset_time.append(result_list[1])
            LOB_subset_bid.append(result_list[2][1])
            LOB_subset_ask.append(result_list[3][1])
            
        
        f.close()
        print(LOB_subset_time[0],LOB_subset_bid[0],LOB_subset_ask[0])
        return [LOB_subset_time,LOB_subset_bid,LOB_subset_ask]
            
            
            
            
            
            
            
        
def Create_LOB_df_Improved(df_element,the_date):
    
    
    LOB_df = pd.DataFrame(df_element).T
    LOB_df['Date'] = the_date
    
    LOB_df = LOB_df.rename(columns={0: 'Time', 1: 'Bid',2: 'Ask'})
                          
    #Directly to S3
    LOB_df.to_csv(f's3://project-b-new/LOB_csv/LOB_csv3/{the_date}-LOB-B03.csv',index = False)
    print(f"The Shape of {the_date} LOB is {LOB_df.shape}")
    
    return LOB_df

In [21]:
Create_LOB_df_Improved(Read_LOB_Improved("s3://project-b-new/dataset-b03/TstB03_2022-01-04LOBs.txt"),'2022-01-04')

This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-04 LOB is (1800000, 4)

,Time,Bid,Ask,Date
0,0,[],[],2022-01-04
1,0.017,[],[],2022-01-04
2,0.034,[],[],2022-01-04
3,0.051,[],[],2022-01-04
4,0.068,[],[],2022-01-04
...,...,...,...,...
1799995,30599.9,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[219, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799996,30599.9,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[219, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799997,30599.9,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[219, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799998,30600,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[218, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799999,30600,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[218, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04

In [22]:
b = pd.read_csv(f's3://project-b-new/LOB_csv/LOB_csv3/2022-01-04-LOB-B03.csv')

In [23]:
b

,Time,Bid,Ask,Date
0,0.000,[],[],2022-01-04
1,0.017,[],[],2022-01-04
2,0.034,[],[],2022-01-04
3,0.051,[],[],2022-01-04
4,0.068,[],[],2022-01-04
...,...,...,...,...
1799995,30599.915,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[219, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799996,30599.932,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[219, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799997,30599.949,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[219, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799998,30599.966,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[218, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04
1799999,30599.983,"[[213, 2], [210, 4], [208, 14], [207, 8], [206...","[[218, 4], [220, 3], [223, 7], [224, 3], [228,...",2022-01-04

In [7]:
exact_date[64:]

['2022-03-09',
 '2022-03-10',
 '2022-03-11',
 '2022-03-12',
 '2022-03-13',
 '2022-03-14',
 '2022-03-15',
 '2022-03-16',
 '2022-03-17',
 '2022-03-18',
 '2022-03-19',
 '2022-03-20',
 '2022-03-21',
 '2022-03-22',
 '2022-03-23',
 '2022-03-24',
 '2022-03-25',
 '2022-03-26',
 '2022-03-27',
 '2022-03-28',
 '2022-03-29',
 '2022-03-30',
 '2022-03-31',
 '2022-04-01',
 '2022-04-02',
 '2022-04-03',
 '2022-04-04',
 '2022-04-05',
 '2022-04-06',
 '2022-04-07',
 '2022-04-08',
 '2022-04-09',
 '2022-04-10',
 '2022-04-11',
 '2022-04-12',
 '2022-04-13',
 '2022-04-14',
 '2022-04-15',
 '2022-04-16',
 '2022-04-17',
 '2022-04-18',
 '2022-04-19',
 '2022-04-20',
 '2022-04-21',
 '2022-04-22',
 '2022-04-23',
 '2022-04-24',
 '2022-04-25',
 '2022-04-26',
 '2022-04-27',
 '2022-04-28',
 '2022-04-29']

In [ ]:
%%time

#2022-01-25 Wrong
#2022-02-09 wrong
#"s3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt" format
for the_date in exact_date[1:]:
    t1 = time.time()
    LOB_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/TstB03_'+the_date+'LOBs.txt')
    

    try:
        print(f"Start Read {the_date} LOB file.")
        Create_LOB_df_Improved(Read_LOB_Improved(LOB_from_s3),the_date)
    except:
        print(f"There is no {the_date} LOB file.")
        continue
        
    t2 = time.time()
    print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

Start Read 2022-01-05 LOB file.

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-05 LOB is (1800000, 4)
The 2022-01-05 is finished. Elapsed time is 453.3572950363159 seconds.
Start Read 2022-01-06 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-06 LOB is (1800000, 4)
The 2022-01-06 is finished. Elapsed time is 470.94711804389954 seconds.
Start Read 2022-01-07 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-07 LOB is (1800000, 4)
The 2022-01-07 is finished. Elapsed time is 468.04927372932434 seconds.
Start Read 2022-01-08 LOB file.
There is no 2022-01-08 LOB file.
Start Read 2022-01-09 LOB file.
There is no 2022-01-09 LOB file.
Start Read 2022-01-10 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-10 LOB is (1800000, 4)
The 2022-01-10 is finished. Elapsed time is 460.33722829818726 seconds.
Start Read 2022-01-11 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-11 LOB is (1800000, 4)
The 2022-01-11 is finished. Elapsed time is 460.7286069393158 seconds.
Start Read 2022-01-12 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-12 LOB is (1800000, 4)
The 2022-01-12 is finished. Elapsed time is 456.57983684539795 seconds.
Start Read 2022-01-13 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-13 LOB is (1800000, 4)
The 2022-01-13 is finished. Elapsed time is 469.44721698760986 seconds.
Start Read 2022-01-14 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-01-14 LOB is (1800000, 4)
The 2022-01-14 is finished. Elapsed time is 477.56981468200684 seconds.
Start Read 2022-01-15 LOB file.
There is no 2022-01-15 LOB file.
Start Read 2022-01-16 LOB file.
There is no 2022-01-16 LOB file.
Start Read 2022-01-17 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row

In [ ]:
%%time

#2022-01-25 Wrong
#2022-02-09 wrong
#2022-02-14 wrong
#"s3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt" format
for the_date in exact_date[41:]:
    t1 = time.time()
    LOB_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/TstB03_'+the_date+'LOBs.txt')
    

    try:
        print(f"Start Read {the_date} LOB file.")
        Create_LOB_df_Improved(Read_LOB_Improved(LOB_from_s3),the_date)
    except:
        print(f"There is no {the_date} LOB file.")
        continue
        
    t2 = time.time()
    print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

Start Read 2022-02-14 LOB file.
This is 0th 18000 row

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
There is no 2022-02-14 LOB file.
Start Read 2022-02-15 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-15 LOB is (1800000, 4)
The 2022-02-15 is finished. Elapsed time is 477.30865955352783 seconds.
Start Read 2022-02-16 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-16 LOB is (1800000, 4)
The 2022-02-16 is finished. Elapsed time is 490.95176005363464 seconds.
Start Read 2022-02-17 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-17 LOB is (1800000, 4)
The 2022-02-17 is finished. Elapsed time is 478.69691252708435 seconds.
Start Read 2022-02-18 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-18 LOB is (1800000, 4)
The 2022-02-18 is finished. Elapsed time is 473.03970170021057 seconds.
Start Read 2022-02-19 LOB file.
There is no 2022-02-19 LOB file.
Start Read 2022-02-20 LOB file.
There is no 2022-02-20 LOB file.
Start Read 2022-02-21 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-21 LOB is (1800000, 4)
The 2022-02-21 is finished. Elapsed time is 461.44152569770813 seconds.
Start Read 2022-02-22 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-22 LOB is (1800000, 4)
The 2022-02-22 is finished. Elapsed time is 430.07224798202515 seconds.
Start Read 2022-02-23 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-02-23 LOB is (1800000, 4)
The 2022-02-23 is finished. Elapsed time is 423.20086765289307 seconds.
Start Read 2022-02-24 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row

In [ ]:
%%time

#2022-01-25 Wrong
#2022-02-09 wrong
#2022-02-14 wrong
#2022-03-31 wrong
#"s3://project-b-data/proj-b/dataset-b01/Tst2022-01-04LOBs.txt" format
for the_date in exact_date[64:]:
    t1 = time.time()
    LOB_from_s3 = 's3://{}/{}'.format(bucket,subfolder+'/TstB03_'+the_date+'LOBs.txt')
    

    try:
        print(f"Start Read {the_date} LOB file.")
        Create_LOB_df_Improved(Read_LOB_Improved(LOB_from_s3),the_date)
    except:
        print(f"There is no {the_date} LOB file.")
        continue
        
    t2 = time.time()
    print('The {} is finished. Elapsed time is {} seconds.'.format(the_date,t2-t1))

Start Read 2022-03-09 LOB file.

/home/ec2-user/anaconda3/envs/python3/lib/python3.6/site-packages/boto3/compat.py:88: PythonDeprecationWarning: Boto3 will no longer support Python 3.6 starting May 30, 2022. To continue receiving service updates, bug fixes, and security updates please upgrade to Python 3.7 or later. More information can be found here: https://aws.amazon.com/blogs/developer/python-support-policy-updates-for-aws-sdks-and-tools/
  warnings.warn(warning, PythonDeprecationWarning)

This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-09 LOB is (1800000, 4)
The 2022-03-09 is finished. Elapsed time is 486.9507899284363 seconds.
Start Read 2022-03-10 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-10 LOB is (1800000, 4)
The 2022-03-10 is finished. Elapsed time is 458.9374132156372 seconds.
Start Read 2022-03-11 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-11 LOB is (1800000, 4)
The 2022-03-11 is finished. Elapsed time is 459.9250440597534 seconds.
Start Read 2022-03-12 LOB file.
There is no 2022-03-12 LOB file.
Start Read 2022-03-13 LOB file.
There is no 2022-03-13 LOB file.
Start Read 2022-03-14 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-14 LOB is (1800000, 4)
The 2022-03-14 is finished. Elapsed time is 438.8767318725586 seconds.
Start Read 2022-03-15 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-15 LOB is (1800000, 4)
The 2022-03-15 is finished. Elapsed time is 437.86486315727234 seconds.
Start Read 2022-03-16 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-16 LOB is (1800000, 4)
The 2022-03-16 is finished. Elapsed time is 460.88793325424194 seconds.
Start Read 2022-03-17 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-17 LOB is (1800000, 4)
The 2022-03-17 is finished. Elapsed time is 436.62470269203186 seconds.
Start Read 2022-03-18 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row
This is 7th 18000 row
This is 8th 18000 row
This is 9th 18000 row
This is 10th 18000 row
This is 11th 18000 row
This is 12th 18000 row
This is 13th 18000 row
This is 14th 18000 row
This is 15th 18000 row
This is 16th 18000 row
This is 17th 18000 row
This is 18th 18000 row
This is 19th 18000 row
This is 20th 18000 row
This is 21th 18000 row
This is 22th 18000 row
This is 23th 18000 row
This is 24th 18000 row
This is 25th 18000 row
This is 26th 18000 row
This is 27th 18000 row
This is 28th 18000 row
This is 29th 18000 row
This is 30th 18000 row
This is 31th 18000 row
This is 32th 18000 row
This is 33th 18000 row
This is 34th 18000 row
This is 35th 18000 row
This is 36th 18000 row
This is 37th 18000 row
This is 38th 18000 row
This is 39th 18000 row
This is 40th 18000 row
This is 41th 18000 row
This is 42th 18000 row
This is 43th 18000 row
This is 44th 18000 row
This is 45th 18000 row
This is 46th 18000 row
This is 47th 18000 row
This is 48th 18000 row
This is 49th 18000 row
This is 50th 18000 row
This is 51th 18000 row
This is 52th 18000 row
This is 53th 18000 row
This is 54th 18000 row
This is 55th 18000 row
This is 56th 18000 row
This is 57th 18000 row
This is 58th 18000 row
This is 59th 18000 row
This is 60th 18000 row
This is 61th 18000 row
This is 62th 18000 row
This is 63th 18000 row
This is 64th 18000 row
This is 65th 18000 row
This is 66th 18000 row
This is 67th 18000 row
This is 68th 18000 row
This is 69th 18000 row
This is 70th 18000 row
This is 71th 18000 row
This is 72th 18000 row
This is 73th 18000 row
This is 74th 18000 row
This is 75th 18000 row
This is 76th 18000 row
This is 77th 18000 row
This is 78th 18000 row
This is 79th 18000 row
This is 80th 18000 row
This is 81th 18000 row
This is 82th 18000 row
This is 83th 18000 row
This is 84th 18000 row
This is 85th 18000 row
This is 86th 18000 row
This is 87th 18000 row
This is 88th 18000 row
This is 89th 18000 row
This is 90th 18000 row
This is 91th 18000 row
This is 92th 18000 row
This is 93th 18000 row
This is 94th 18000 row
This is 95th 18000 row
This is 96th 18000 row
This is 97th 18000 row
This is 98th 18000 row
This is 99th 18000 row
0.0 [] []
The Shape of 2022-03-18 LOB is (1800000, 4)
The 2022-03-18 is finished. Elapsed time is 406.05641436576843 seconds.
Start Read 2022-03-19 LOB file.
There is no 2022-03-19 LOB file.
Start Read 2022-03-20 LOB file.
There is no 2022-03-20 LOB file.
Start Read 2022-03-21 LOB file.
This is 0th 18000 row
This is 1th 18000 row
This is 2th 18000 row
This is 3th 18000 row
This is 4th 18000 row
This is 5th 18000 row
This is 6th 18000 row